### ISSUE TITLE
Weird OPA error - concurrent map writes

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1941]
# Expected Behavior
OPA worked as expected

# Actual Behavior
Weird error:
“fatal error: concurrent map writes”

Callstack:
```
/home/travis/gopath/src/github.com/open-policy-agent/opa/plugins/logs/plugin.go:296 +0x3f6 fp=0xc0005770e8 sp=0xc000576c48 pc=0xd95f76
github.com/open-policy-agent/opa/plugins/logs.(*Plugin).Log(0xc0002084d0, 0x109b9a0, 0xc00052b6e0, 0xc000a3c000, 0x0, 0x0)
/home/travis/gopath/src/github.com/open-policy-agent/opa/plugins/logs/plugin.go:511 +0x134 fp=0xc000576c48 sp=0xc000576ba8 pc=0xd97604
github.com/open-policy-agent/opa/plugins/logs.(*Plugin).maskEvent(0xc0002084d0, 0x109b9a0, 0xc00052b6e0, 0x1087b00, 0xc00052bc50, 0xc000670240, 0x2, 0xc000484420)
/home/travis/gopath/src/github.com/open-policy-agent/opa/rego/rego.go:258 +0x178 fp=0xc000576ba8 sp=0xc000576b38 pc=0xc164f8
github.com/open-policy-agent/opa/rego.PreparedEvalQuery.Eval(0xc000522380, 0xc00042cb10, 0x109b9a0, 0xc00052b6e0, 0xc000576c28, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
/home/travis/gopath/src/github.com/open-policy-agent/opa/rego/rego.go:1224 +0x458 fp=0xc000576b38 sp=0xc0005769b8 pc=0xc1c488
github.com/open-policy-agent/opa/rego.(*Rego).eval(0xc000522380, 0x109b9a0, 0xc00052b6e0, 0xc000132000, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/travis/gopath/src/github.com/open-policy-agent/opa/topdown/query.go:252 +0x320 fp=0xc0005769b8 sp=0xc000576940 pc=0xbf7850
github.com/open-policy-agent/opa/topdown.(*Query).Iter(0xc000576a48, 0x109b9a0, 0xc00052b6e0, 0xc000354720, 0x0, 0x0)
/home/travis/gopath/src/github.com/open-policy-agent/opa/topdown/query.go:266 +0x5d fp=0xc000576940 sp=0xc000576908 pc=0xbf7b2d
github.com/open-policy-agent/opa/topdown.(*Query).startTimer(0xc000576a48, 0xf8fca2, 0xf)
/home/travis/gopath/src/github.com/open-policy-agent/opa/metrics/metrics.go:91 +0xc4 fp=0xc000576908 sp=0xc0005768c0 pc=0xad4b04
github.com/open-policy-agent/opa/metrics.(*metrics).Timer(0xc00048c080, 0xf8fca2, 0xf, 0xf52100, 0xc0003547e0)
/home/travis/.gimme/versions/go1.12.8.linux.amd64/src/runtime/map_faststr.go:291 +0x40f fp=0xc0005768c0 sp=0xc000576858 pc=0x75efbf
runtime.mapassign_faststr(0xe971a0, 0xc000564030, 0xf8fca2, 0xf, 0x18199e0)
/home/travis/.gimme/versions/go1.12.8.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc000576858 sp=0xc000576828 pc=0x779862
runtime.throw(0xf944bc, 0x15)
goroutine 57 [running]:
```

Not sure how to reproduce...

OPA version - 0.13.5

**Comment by tsandall** [comment]
This appears to be the same panic reported here: https://github.com/open-policy-agent/opa/issues/1827

The problem was the internal metrics object (which was not threadsafe at the time) was being shared across multiple goroutines accidentally. When the decision logger evaluated the masking policy, the metrics would be written and so that's where the race came from (since the logger can be invoked by multiple server goroutines). Since then we fixed the `rego` package to stop sharing the metrics object unnecessarily and made the metrics objects threadsafe.

I'd recommend updating to v0.15.1 or v0.14.2 which include these fixes.

Closing this for now. Thanks for reporting it though!
