### ISSUE TITLE
[envoy plugin] runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1963]
# Expected Behavior
Policy evaluated and the request is authorized/denied

# Actual Behavior
When the bundle does not have a revision set, the following error is raise. Looking at the code, look like a revision is required for the logging:

```
oauth-client-77c4954756-j7q8n opa panic: runtime error: invalid memory address or nil pointer dereference
oauth-client-77c4954756-j7q8n opa       panic: runtime error: invalid memory address or nil pointer dereference
oauth-client-77c4954756-j7q8n opa [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf15ed8]
oauth-client-77c4954756-j7q8n opa 
oauth-client-77c4954756-j7q8n opa goroutine 83 [running]:
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/internal.(*envoyExtAuthzGrpcServer).log(0xc00017b620, 0x1318520, 0xc00014f740, 0x10eb8a0, 0xc00014fc50, 0x0, 0x0, 0x0, 0xc0005193a0, 0xc000413340)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/internal/internal.go:383 +0xf8
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/internal.(*envoyExtAuthzGrpcServer).Check.func1(0xc00017b620, 0x1318520, 0xc00014f740, 0xc0002b5de8, 0xc000413900, 0xc000413b20, 0xc000413b18)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/internal/internal.go:166 +0x8e
oauth-client-77c4954756-j7q8n opa panic(0x11097e0, 0x1b8a190)
oauth-client-77c4954756-j7q8n opa       /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513 +0x1b9
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/rego.preparedQuery.newEvalContext(0x0, 0x0, 0x1318520, 0xc00014f740, 0xc0004135c8, 0x3, 0x3, 0xc000389ec0, 0xc0004134c8, 0xec205d, ...)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/rego/rego.go:209 +0x47
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/rego.PreparedEvalQuery.Eval(0x0, 0x0, 0x1318520, 0xc00014f740, 0xc0004135c8, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/rego/rego.go:282 +0x99
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/internal.(*envoyExtAuthzGrpcServer).eval.func1(0x1308d00, 0xc000369470, 0xc00014f740, 0xc000446e90)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/internal/internal.go:330 +0x30b
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/storage.Txn(0x1318520, 0xc00014f740, 0x131d920, 0xc0000b2d70, 0xc000369400, 0x0, 0xc000413800, 0xc000413850, 0x0)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/open-policy-agent/opa/storage/storage.go:95 +0xe1
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/internal.(*envoyExtAuthzGrpcServer).eval(0xc00017b620, 0x1318520, 0xc00014f740, 0x13193e0, 0xc000368450, 0x0, 0x0, 0x0, 0xc000413b18, 0xc0004138f8, ...)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/internal/internal.go:300 +0x188
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/internal.(*envoyExtAuthzGrpcServer).Check(0xc00017b620, 0x1318520, 0xc00014f740, 0xc00014f770, 0x0, 0x0, 0x0)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/internal/internal.go:207 +0x450
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2._Authorization_Check_Handler(0x11aa420, 0xc00017b620, 0x1318520, 0xc00014f740, 0xc00017b080, 0x0, 0x0, 0x0, 0xc0003443c0, 0x1da)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/github.com/envoyproxy/go-control-plane/envoy/service/auth/v2/external_auth.pb.go:342 +0x23e
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c1a20, 0x131cec0, 0xc000329c80, 0xc0002c3900, 0xc000256990, 0x1b8abc0, 0x0, 0x0, 0x0)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc/server.go:995 +0x485
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000c1a20, 0x131cec0, 0xc000329c80, 0xc0002c3900, 0x0)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc/server.go:1275 +0xdf9
oauth-client-77c4954756-j7q8n opa github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002da4b4, 0xc0000c1a20, 0x131cec0, 0xc000329c80, 0xc0002c3900)
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc/server.go:710 +0x9f
oauth-client-77c4954756-j7q8n opa created by github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
oauth-client-77c4954756-j7q8n opa       /home/travis/gopath/src/github.com/open-policy-agent/opa-istio-plugin/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

# Steps to Reproduce the Problem

  1. Create a bundle without a revision
  2. Run OPA with Envoy plugin
  3. Try to evaluate a policy using the GRPC api

# Additional Info

**Comment by ashutosh-narkar** [comment]
@omerlh thanks for reporting this. This error comes if a `nil` result is passed to the decision logger. We will fix this asap.
