### ISSUE TITLE
panic: rego package panics when partial evaluation is executed with tracing enabled

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2007]
```
$ docker run openpolicyagent/opa:0.16.1 eval -p --explain=full 'data'
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/open-policy-agent/opa/rego.(*Rego).partial(0xc0001b8000, 0x10b5520, 0xc00002a030, 0xc0001dc000, 0x0, 0x0, 0x0)
	/src/rego/rego.go:1701 +0xbf0
github.com/open-policy-agent/opa/rego.PreparedPartialQuery.Partial(0xc0001b8000, 0xc000189ca0, 0x10b5520, 0xc00002a030, 0xc0001960e0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/src/rego/rego.go:311 +0x170
github.com/open-policy-agent/opa/cmd.eval(0xc0001736e0, 0x1, 0x3, 0x100, 0xc0001882d0, 0x1, 0x1, 0x1627c90, 0x0, 0x0, ...)
	/src/cmd/eval.go:364 +0xe10
github.com/open-policy-agent/opa/cmd.init.3.func2(0xc00017c780, 0xc0001736e0, 0x1, 0x3)
	/src/cmd/eval.go:199 +0xde
github.com/spf13/cobra.(*Command).execute(0xc00017c780, 0xc000173680, 0x3, 0x3, 0xc00017c780, 0xc000173680)
	/src/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x15c8520, 0x15c8520, 0xc0000bff88, 0x730d9f)
	/src/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/src/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/src/main.go:15 +0x32
```

**Comment by tsandall** [comment]
@patrick-east can you take a look at this? It seems like some state is not being copied between the evaluation context and rego structures.
