### ISSUE TITLE
Panic during compile

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#257]
Nested references that do not refer directly to a rule trigger a panic.

```
package a.b

p = data.a.c[input.foo]
```

```
package a.c

x = true
```

```
torin:~/rego$ docker run -it --rm -v $PWD:/rego openpolicyagent/opa:0.4.2 run /rego
panic: runtime error: hash of unhashable type ast.Ref

goroutine 1 [running]:
panic(0x86fce0, 0xc4203716c0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/open-policy-agent/opa/ast.(*Compiler).GetRulesForVirtualDocument(0xc4200f00c0, 0xc4202cf2c0, 0x4, 0x4, 0xc420272ed0, 0x1, 0xc4202cf2c0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:251 +0x6c
github.com/open-policy-agent/opa/ast.(*Compiler).GetRules(0xc4200f00c0, 0xc4202cf2c0, 0x4, 0x4, 0x4, 0x4, 0xc420185458)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:323 +0x9c
github.com/open-policy-agent/opa/ast.(*ruleGraphBuilder).Visit(0xc4203716a0, 0x8b76c0, 0xc4202cf160, 0xb05fe0, 0xc4203716a0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:1091 +0xd1
github.com/open-policy-agent/opa/ast.Walk(0xb05fe0, 0xc4203716a0, 0x8b76c0, 0xc4202cf160)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/visit.go:22 +0xaf
github.com/open-policy-agent/opa/ast.Walk(0xb05fe0, 0xc4203716a0, 0x897220, 0xc42029b350)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/visit.go:49 +0x88f
github.com/open-policy-agent/opa/ast.Walk(0xb05fe0, 0xc4203716a0, 0x897460, 0xc42029b320)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/visit.go:41 +0xa80
github.com/open-policy-agent/opa/ast.(*Compiler).setRuleGraph(0xc4200f00c0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:658 +0x174
github.com/open-policy-agent/opa/ast.(*Compiler).(github.com/open-policy-agent/opa/ast.setRuleGraph)-fm()
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:169 +0x2a
github.com/open-policy-agent/opa/ast.(*Compiler).compile(0xc4200f00c0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:478 +0x4e
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc4200f00c0, 0xc42039ab40)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/ast/compile.go:196 +0x169
github.com/open-policy-agent/opa/runtime.compileAndStoreInputs(0xc4200e4db0, 0xc4201000a0, 0xb079e0, 0xc4203b4358, 0xc4203b4358, 0x0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/runtime/runtime.go:248 +0x14f
github.com/open-policy-agent/opa/runtime.(*Runtime).init(0xc420022088, 0xb0bea0, 0xc420010250, 0xc42009cd00, 0x0, 0x0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/runtime/runtime.go:133 +0x625
github.com/open-policy-agent/opa/runtime.(*Runtime).Start(0xc420022088, 0xc42009cd00)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/runtime/runtime.go:88 +0x5e
github.com/open-policy-agent/opa/cmd.init.1.func1(0xc420086d80, 0xc420011b60, 0x1, 0x1)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/cmd/run.go:93 +0x82
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).execute(0xc420086d80, 0xc420011b20, 0x1, 0x1, 0xc420086d80, 0xc420011b20)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb2a280, 0x0, 0xb2a280, 0xc4200b3ee8)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).Execute(0xb2a280, 0x0, 0x0)
	/home/travis/gopath/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/home/travis/gopath/src/github.com/open-policy-agent/opa/main.go:12 +0x31
```

**Comment by tsandall** [comment]
This is caused by GetRules, GetRulesExact, etc. not handling all terms as ref operands. In this case, it is nested refs though same would happen when we eventually support composite literals as ref operands.
