### ISSUE TITLE
Panic in opa eval

### ISSUE THREAD

**Issue by vazirim** [open-policy-agent/opa#2691]
## Expected Behavior

Opa eval should not panic even if the input is possibly ill-formed

## Actual Behavior

panic

## Steps to Reproduce the Problem

Here's the rego code (not sure if this is valid, but it seems to be according to the grammar):
```
package ex

violation(protocol)[server.id] {                              
    server := input.servers[_]
    server.protocols[_] == protocol                 
}
```

input.json:
```
{
    "servers": [
        {"id": "app", "protocols": ["https", "ssh"], "ports": ["p1", "p2", "p3"]},
        {"id": "db", "protocols": ["mysql"], "ports": ["p3"]},
        {"id": "cache", "protocols": ["memcache"], "ports": ["p3"]},
        {"id": "ci", "protocols": ["http"], "ports": ["p1", "p2"]},
        {"id": "busybox", "protocols": ["telnet"], "ports": ["p1"]}
    ]
}
```

```
opa eval -i input.json -d ex.rego 'data.ex.violation("mysql")'
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x143ebb8]

goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.(*Compiler).compile.func1()
        /go/src/github.com/open-policy-agent/opa/ast/compile.go:881 +0x73
panic(0x17d91e0, 0x1f27a10)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/open-policy-agent/opa/ast.(*TypeEnv).Get(0xc0001fdef0, 0x1871c80, 0x0, 0x19f6720, 0xc0002260e0)
        /go/src/github.com/open-policy-agent/opa/ast/env.go:29 +0x58
github.com/open-policy-agent/opa/ast.(*typeChecker).checkRule(0xc000207e60, 0xc0001fdee0, 0xc00017b380)
        /go/src/github.com/open-policy-agent/opa/ast/check.go:174 +0x3a1
github.com/open-policy-agent/opa/ast.(*typeChecker).CheckTypes(0xc000207e60, 0xc0001fdee0, 0xc0001fdeb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x5000104)
        /go/src/github.com/open-policy-agent/opa/ast/check.go:103 +0x168
github.com/open-policy-agent/opa/ast.(*Compiler).checkTypes(0xc0001ec000)
        /go/src/github.com/open-policy-agent/opa/ast/compile.go:845 +0x117
github.com/open-policy-agent/opa/ast.(*Compiler).runStage(0xc0001ec000, 0x18de63a, 0x19, 0xc000169c60)
        /go/src/github.com/open-policy-agent/opa/ast/compile.go:866 +0x46
github.com/open-policy-agent/opa/ast.(*Compiler).compile(0xc0001ec000)
        /go/src/github.com/open-policy-agent/opa/ast/compile.go:886 +0x125
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc0001ec000, 0xc0001f6b98)
        /go/src/github.com/open-policy-agent/opa/ast/compile.go:351 +0x2b4
github.com/open-policy-agent/opa/bundle.writeModules(0x19f9320, 0xc0000260a8, 0x1a024c0, 0xc00017ab40, 0x19e6fc0, 0xc0001ea4b0, 0xc0001ec000, 0x19ff280, 0xc0001cf880, 0xc0001ea120, ...)
        /go/src/github.com/open-policy-agent/opa/bundle/store.go:397 +0x5d5
github.com/open-policy-agent/opa/bundle.activateBundles(0xc0001f7320, 0xc0000260a8, 0x1a024c0)
        /go/src/github.com/open-policy-agent/opa/bundle/store.go:243 +0x817
github.com/open-policy-agent/opa/bundle.Activate(...)
        /go/src/github.com/open-policy-agent/opa/bundle/store.go:161
github.com/open-policy-agent/opa/rego.(*Rego).compileModules(0xc000186b40, 0x19f9320, 0xc0000260a8, 0x19e6fc0, 0xc0001ea4b0, 0x19ff280, 0xc0001cf880, 0x0, 0x0)
        /go/src/github.com/open-policy-agent/opa/rego/rego.go:1609 +0x1b5
github.com/open-policy-agent/opa/rego.(*Rego).prepare(0xc000186b40, 0x19f9320, 0xc0000260a8, 0x0, 0xc0001f74c0, 0x1, 0x1, 0x0, 0xc00017aac0)
        /go/src/github.com/open-policy-agent/opa/rego/rego.go:1436 +0x1f4
github.com/open-policy-agent/opa/rego.(*Rego).PrepareForEval(0xc000186b40, 0x19f9320, 0xc0000260a8, 0x0, 0x0, 0x0, 0x1, 0x1f64198, 0x0, 0x0)
        /go/src/github.com/open-policy-agent/opa/rego/rego.go:1351 +0x4e2
github.com/open-policy-agent/opa/cmd.eval(0xc00018a190, 0x1, 0x5, 0x0, 0xc000168390, 0x1, 0x1, 0x1f64198, 0x0, 0x0, ...)
        /go/src/github.com/open-policy-agent/opa/cmd/eval.go:265 +0x9b4
github.com/open-policy-agent/opa/cmd.init.4.func2(0xc000182c80, 0xc00018a190, 0x1, 0x5)
        /go/src/github.com/open-policy-agent/opa/cmd/eval.go:204 +0xde
github.com/spf13/cobra.(*Command).execute(0xc000182c80, 0xc00018a140, 0x5, 0x5, 0xc000182c80, 0xc00018a140)
        /go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1f332a0, 0xc00005a750, 0xc0000bbf50, 0x100545f)
        /go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /go/src/github.com/open-policy-agent/opa/main.go:15 +0x31
```

**Comment by patrick-east** [comment]
The panic has been addressed in this change https://github.com/open-policy-agent/opa/commit/b9e5ef5b07207f1cd57e7f8765d78d8a0ec7130a as part of a fix for #2662

The fix will be included in the next OPA release.

**Comment by vazirim** [comment]
@patrick-east Thank you! 
Is this valid Rego?

**Comment by patrick-east** [comment]
The example with:

```rego
violation(protocol)[server.id] {
    ...
}
```

Is not really valid rego. Rule definitions can have arguments like `violation(protocol)` or can be "partial" rules (or "incremental" as its referenced in the docs) like `violation[server.id]`.

If you want to have a rule with arguments like `violation(protocol)` define a set built by iterating over something in the rule body you would typically want to use a set comprehension like:

```rego
violation(protocol) = { server.id |
	server := input.servers[_]
	server.protocols[_] == protocol
}
```
Full example: https://play.openpolicyagent.org/p/YShJbPMWRW

**Comment by vazirim** [comment]
Thanks so much.
