### ISSUE TITLE
rest client used by status/bundle plugins is leaking sockets

### ISSUE THREAD

**Issue by gshively11** [open-policy-agent/opa#2859]
## Expected Behavior

Should be able to run the OPA server with discovery/bundle/status plugins indefinitely without leaking sockets

## Actual Behavior

After ~30 minutes, I being to receive errors related to DNS resolution:

```
{"level":"error","msg":"Discovery download failed: request failed: Get \"https://<redacted>/bundle.tar.gz\": dial tcp: lookup <redacted>: no such host","name":"<redacted>","plugin":"discovery","time":"2020-11-03T09:54:13-07:00"}
```

I also receive this error periodically:

```
2020/11/03 09:56:43 http: Accept error: accept tcp [::]:8484: accept: too many open files; retrying in 5ms
```

I'm pretty sure it's related to improperly closed requests, and timeouts 

## Steps to Reproduce the Problem

* OPA version 0.25.0-dev
Run the server with discovery/bundle/status plugins enabled on a quick interval (~30s) for an extended period of time.

## Additional Info

I'm pretty sure this is due to insufficient timeout configuration and missing connection closing in `plugins/rest/rest.go`. 

See these posts for more info:
- https://stackoverflow.com/questions/37454236/net-http-server-too-many-open-files-error
- https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
- https://github.com/golang/go/issues/18588

**Comment by gshively11** [comment]
I'm going to attempt a PR on this one shortly

**Comment by gshively11** [comment]
Gah, actually I think OPA is innocent on this one.  I suspect this is caused by a healthcheck process I have bundled with it.  Will close this once I confirm...

**Comment by anderseknert** [comment]
Heh, yeah I tried reproducing here with discovery polling set to 1-2 seconds, but netstat not showing any increase in sockets used after the initial ones have been established.

**Comment by gshively11** [comment]
Hmm, actually I've ruled out my healthcheck process, it's not running and it's still hanging onto tcp connections.  `lsof -p <pid>` for the process shows a steadily growing list of `TCP localhost:8484->localhost:<random_port> (ESTABLISHED)`

**Comment by gshively11** [comment]
From a stack dump, there's a lot of goroutines like this
```
goroutine 417 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x2e7ba28, 0x72, 0x1f33d60)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000bd0f98, 0x72, 0xc000c56000, 0x205, 0x205)
	/usr/local/Cellar/go/1.15.2/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.15.2/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000bd0f80, 0xc000c56000, 0x205, 0x205, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc000bd0f80, 0xc000c56000, 0x205, 0x205, 0x203000, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000b03d8, 0xc000c56000, 0x205, 0x205, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0006ad8c0, 0xc000c56000, 0x205, 0x205, 0x8f80008c6d9a9532, 0xefbe4786e49b69c1, 0xc000b7b2b0)
	/usr/local/Cellar/go/1.15.2/libexec/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00044ad00, 0x1f30640, 0xc0006ad8c0, 0x100d645, 0x1c2e480, 0x1d40f80)
	/usr/local/Cellar/go/1.15.2/libexec/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00044aa80, 0x2ec7538, 0xc0000b03d8, 0x5, 0xc0000b03d8, 0xa81a664ba2bfe8a1)
	/usr/local/Cellar/go/1.15.2/libexec/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00044aa80, 0x0, 0x0, 0xc000bb9401)
	/usr/local/Cellar/go/1.15.2/libexec/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/Cellar/go/1.15.2/libexec/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00044aa80, 0xc000c5a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/crypto/tls/conn.go:1252 +0x15f
net/http.(*connReader).Read(0xc0007cd620, 0xc000c5a000, 0x1000, 0x1000, 0x400, 0x2ba3100, 0x203000)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/http/server.go:798 +0x1ad
bufio.(*Reader).fill(0xc00073b0e0)
	/usr/local/Cellar/go/1.15.2/libexec/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).ReadSlice(0xc00073b0e0, 0xa, 0x28, 0xc000b7b988, 0x100fa70, 0xc000261000, 0x100)
	/usr/local/Cellar/go/1.15.2/libexec/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc00073b0e0, 0xc000b7b990, 0xc000780000, 0x2a00e98, 0x0, 0x10103d8, 0x30)
	/usr/local/Cellar/go/1.15.2/libexec/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc0007cd650, 0xc000261000, 0x0, 0x203000, 0x2a0bc98, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/textproto/reader.go:58 +0x6c
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/textproto/reader.go:39
net/http.readRequest(0xc00073b0e0, 0x0, 0xc000261000, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/http/request.go:1012 +0xaa
net/http.(*conn).readRequest(0xc0008915e0, 0x1f49820, 0xc0007be280, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/http/server.go:984 +0x19a
net/http.(*conn).serve(0xc0008915e0, 0x1f49820, 0xc0007be280)
	/usr/local/Cellar/go/1.15.2/libexec/src/net/http/server.go:1851 +0x705
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.15.2/libexec/src/net/http/server.go:2969 +0x36c
```

**Comment by gshively11** [comment]
Nope, it's a gah, had a zombie process on my machine spamming the opa server.  Apologies for the confusion.  Thanks for taking a look @anderseknert .
