### ISSUE TITLE
wasm: json.patch built-in function causes panic or runtime error

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#2949]
The wasm e2e integration tests are panicking or generating runtime errors when the new `json.patch` built-in function cases are run. I'm filing this issue to track and put an exception in place.

**Comment by srenatus** [comment]
For the set-related functions, only those with `want_result: []` bomb, the rest error in different ways, related to the way we go to json arrays to compare sets:

```
=== RUN   TestWasmE2E/test/cases/testdata/jsonpatch/set.yaml/jsonpatch/set
    external_test.go:99: expected [{"x": {"bar": ["c", "d", "a"], "foo": ["b"]}}] but got [{"x": {"bar": ["d", "c", "a"], "foo": ["b"]}}]
=== RUN   TestWasmE2E/test/cases/testdata/jsonpatch/set.yaml/jsonpatch/set#01
    external_test.go:99: expected [{"x": {"foo": ["a", "c"]}}] but got [{"x": {"foo": ["c", "a"]}}]
=== RUN   TestWasmE2E/test/cases/testdata/jsonpatch/set.yaml/jsonpatch/set#02
    external_test.go:99: expected [{"x": {"foo": ["a", "b", "c", "d"]}}] but got [{"x": {"foo": ["c", "b", "a", "d"]}}]
=== RUN   TestWasmE2E/test/cases/testdata/jsonpatch/set.yaml/jsonpatch/set#03
--- FAIL: TestWasmE2E (1.22s)
```

**Comment by srenatus** [comment]
As per the panic, I'm not sure if this is really specific to `json.patch`: We see `syscall frame is no longer valid`, similar to what's described here: https://github.com/wasmerio/wasmer-go/issues/93

```
fatal error: exitsyscall: syscall frame is no longer valid

goroutine 50 [running, locked to thread]:
runtime.throw(0x45c70d0, 0x2d)
        /nix/store/5qvydaa3fvj1078kphkmmfvcb7mcvmaq-go-1.15.6/share/go/src/runtime/panic.go:1116 +0x72 fp=0xc000135870 sp=0xc000135840 pc=0x4039192
runtime.exitsyscall()
        /nix/store/5qvydaa3fvj1078kphkmmfvcb7mcvmaq-go-1.15.6/share/go/src/runtime/proc.go:3239 +0x22c fp=0xc0001358a0 sp=0xc000135870 pc=0x406bd0c
runtime.cgocall(0x44bb050, 0xc000135908, 0xc000503200)
        /nix/store/5qvydaa3fvj1078kphkmmfvcb7mcvmaq-go-1.15.6/share/go/src/runtime/cgocall.go:152 +0x9e fp=0xc0001358d8 sp=0xc0001358a0 pc=0x4005d3e
github.com/wasmerio/go-ext-wasm/wasmer._Cfunc_wasmer_instance_call(0xc6d5120, 0xc60cf10, 0xc0001117e0, 0x1, 0xc0001117f0, 0xc000000001, 0x2)
        _cgo_gotypes.go:798 +0x4d fp=0xc000135908 sp=0xc0001358d8 pc=0x43abd6d
github.com/wasmerio/go-ext-wasm/wasmer.cWasmerInstanceCall(...)
        /Users/stephan/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.1/wasmer/bridge.go:503
github.com/wasmerio/go-ext-wasm/wasmer.getExportsFromInstance.func2(0xc0006780c0, 0x1, 0x1, 0xc000187ac8, 0x4323105, 0xc000a349c0, 0x319737af)
        /Users/stephan/go/pkg/mod/github.com/wasmerio/go-ext-wasm@v0.3.1/wasmer/instance.go:365 +0x21f fp=0xc000135a70 sp=0xc000135908 pc=0x43ad0ff
github.com/open-policy-agent/opa/internal/wasm/sdk/internal/wasm.(*VM).Eval.func2(0xc000135c28, 0xc000f82d80, 0x1f73c)
        /Users/stephan/Sources/open-policy-agent/opa/internal/wasm/sdk/internal/wasm/vm.go:277 +0xb7 fp=0xc000135ad8 sp=0xc000135a70 pc=0x444cc17
github.com/open-policy-agent/opa/internal/wasm/sdk/internal/wasm.(*VM).Eval(0xc000f82d80, 0x46506c0, 0xc0000261e8, 0x0, 0x0, 0x4653460, 0xc000431f20, 0x0, 0x0, 0x0, ...)
        /Users/stephan/Sources/open-policy-agent/opa/internal/wasm/sdk/internal/wasm/vm.go:278 +0x469 fp=0xc000135c48 sp=0xc000135ad8 pc=0x44496e9
github.com/open-policy-agent/opa/internal/wasm/sdk/opa.(*OPA).Eval(0xc00013fb20, 0x46506c0, 0xc0000261e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/stephan/Sources/open-policy-agent/opa/internal/wasm/sdk/opa/opa.go:180 +0x17b fp=0xc000135d38 sp=0xc000135c48 pc=0x444d3fb
github.com/open-policy-agent/opa/internal/wasm/sdk/test/e2e.TestWasmE2E.func1(0xc000503080)
        /Users/stephan/Sources/open-policy-agent/opa/internal/wasm/sdk/test/e2e/external_test.go:98 +0x4db fp=0xc000135f80 sp=0xc000135d38 pc=0x44b96db
testing.tRunner(0xc000503080, 0xc000a46ec0)
        /nix/store/5qvydaa3fvj1078kphkmmfvcb7mcvmaq-go-1.15.6/share/go/src/testing/testing.go:1123 +0xef fp=0xc000135fd0 sp=0xc000135f80 pc=0x40f898f
runtime.goexit()
        /nix/store/5qvydaa3fvj1078kphkmmfvcb7mcvmaq-go-1.15.6/share/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000135fd8 sp=0xc000135fd0 pc=0x4070b41
created by testing.(*T).Run
        /nix/store/5qvydaa3fvj1078kphkmmfvcb7mcvmaq-go-1.15.6/share/go/src/testing/testing.go:1168 +0x2b3
```

Poking around randomly, it seems to be triggered when accessing `i.builtinResult`.

From the go-wasmer discussion linked above,
> When the Go runtime has to grow a stack, the stack is copied and all pointers on the stack must be updated to the offset from the proper start of the new stack. However uintptr is not treated specially in Go, and so is not updated when this occurs. This results in the pointer becoming invalid.

I'm wondering if anything that causes "stack growing" wouldn't lead to our `*VM` (or one or more than one of its embedded pointers) pointing to the wrong thing...? I suppose one approach to go forward here could be to narrow down what is passed through the instance context for builtin eval.

**Comment by srenatus** [comment]
OTOH the [release notes for 0.3.0](https://github.com/wasmerio/wasmer-go/releases/tag/0.3.0) explicitly state that what we're doing should be OK, I think:
> InstanceContext supports user data with any reference types or types that include any reference types or other Go pointers

Need to dig in some more...

**Comment by srenatus** [comment]
I think there is some re-work to do when we get our wasm SDK to wasmer 1.0.0. (Judging from the new API, https://pkg.go.dev/github.com/wasmerio/wasmer-go/wasmer.) However, the fine folks at wasmer seem to still be working on the docs, so I'd wait for those instead of poking at the dark. 🤔
