### ISSUE TITLE
make test fails on OSX after; internal/wasm: Switch to wasmtime-go runtime

### ISSUE THREAD

**Issue by johanneslarsson** [open-policy-agent/opa#3168]
This commit seem to be responsible: https://github.com/open-policy-agent/opa/commit/6461ec20214cd16e5c0ebd8ad647bbd80d5004d4

## Expected Behaviour
make test to run succesful after a fresh clone

## Actual Behaviour
```
make test

<removed>

?   	github.com/open-policy-agent/opa/internal/wasm/sdk/examples/loaders	[no test files]
ok  	github.com/open-policy-agent/opa/internal/wasm/sdk/internal/wasm	5.608s
PLAN:
-----
*ir.Policy Policy
| *ir.Static Static (1 strings, 2 files)
| | *ir.StringConst &{Value:x}
| | *ir.StringConst &{Value:module.rego}
| | *ir.StringConst &{Value:<query>}
| *ir.Plans &{Plans:[Plan eval (2 blocks)]}
| | *ir.Plan Plan eval (2 blocks)
| | | *ir.Block Block (1 statements)
| | | | *ir.MakeStringStmt &{Index:0 Target:2 Location:{Index:0 Col:0 Row:0 file: text:}}
| | | *ir.Block Block (5 statements)
| | | | *ir.CallStmt &{Func:g0.data.p.a Args:[0 1] Result:3 Location:{Index:1 Col:1 Row:1 file:<query> text:data.p.a = x}}
| | | | *ir.AssignVarStmt &{Source:3 Target:4 Location:{Index:1 Col:1 Row:1 file:<query> text:data.p.a = x}}
| | | | *ir.MakeObjectStmt &{Target:5 Location:{Index:1 Col:1 Row:1 file:<query> text:data.p.a = x}}
| | | | *ir.ObjectInsertStmt &{Key:2 Value:4 Object:5 Location:{Index:1 Col:1 Row:1 file:<query> text:data.p.a = x}}
| | | | *ir.ResultSetAdd &{Value:5 Location:{Index:1 Col:1 Row:1 file:<query> text:data.p.a = x}}
| *ir.Funcs Funcs (1 funcs)
| | *ir.Func g0.data.p.a (2 params: [0 1], 3 blocks, path: [g0 p a])
| | | *ir.Block Block (6 statements)
| | | | *ir.ResetLocalStmt &{Target:3 Location:{Index:0 Col:1 Row:2 file:module.rego text:a = true}}
| | | | *ir.MakeBooleanStmt &{Value:true Target:4 Location:{Index:0 Col:5 Row:2 file:module.rego text:true}}
| | | | *ir.MakeBooleanStmt &{Value:false Target:5 Location:{Index:0 Col:5 Row:2 file:module.rego text:true}}
| | | | *ir.NotEqualStmt &{A:4 B:5 Location:{Index:0 Col:5 Row:2 file:module.rego text:true}}
| | | | *ir.MakeBooleanStmt &{Value:true Target:6 Location:{Index:0 Col:1 Row:2 file:module.rego text:a = true}}
| | | | *ir.AssignVarOnceStmt &{Target:3 Source:6 Location:{Index:0 Col:1 Row:2 file:module.rego text:a = true}}
| | | *ir.Block Block (2 statements)
| | | | *ir.IsDefinedStmt &{Source:3 Location:{Index:0 Col:1 Row:2 file:module.rego text:a = true}}
| | | | *ir.AssignVarOnceStmt &{Target:2 Source:3 Location:{Index:0 Col:1 Row:2 file:module.rego text:a = true}}
| | | *ir.Block Block (1 statements)
| | | | *ir.ReturnLocalStmt &{Source:2 Location:{Index:0 Col:1 Row:2 file:module.rego text:a = true}}
planner debug:
{data.p.a = x ref data.p.a: all nodes have 0 children, break}
{data.p.a = x no optimization of data.p.a: no vars seen before trie descend encountered no children}
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0xc000225560
stack: frame={sp:0xc0002250e0, fp:0xc0002250f0} stack=[0xc00021d010,0xc000225410)
000000c000224fe0:  000000c000225000  0000000004052ec5 <runtime.sigNotOnStack+133> 
000000c000224ff0:  000000000522e8ce  0000000000000039 
000000c000225000:  000000c000225058  0000000004051ea5 <runtime.adjustSignalStack+645> 
000000c000225010:  0000000000000010  000000c000225040 
000000c000225020:  000000c000225068  0000000000000018 
000000c000225030:  0100000000000018  000000000514c8c0 
000000c000225040:  000000000e765000  0000000000010000 
000000c000225050:  0000000000000001  000000c0002250d0 
000000c000225060:  0000000004051b11 <runtime.sigtrampgo+369>  000000c000000010 
000000c000225070:  000000c00005a900  000000c000225090 
000000c000225080:  0000000000000000  000000c000100900 
000000c000225090:  0000000000000000  0000000000000000 
000000c0002250a0:  0000000000000000  0000000000000000 
000000c0002250b0:  0000000000000000  000000c00021aa80 
000000c0002250c0:  000000c000225560  000000c0002255c8 
000000c0002250d0:  000000c000225120  0000000004076233 <runtime.sigtramp+51> 
000000c0002250e0: <000000c000000010 !000000c000225560 
000000c0002250f0: >000000c0002255c8  000000c0002255c8 
000000c000225100:  ba5cb4a606f300ac  0000000000000009 
000000c000225110:  000080c0003c6000  000080c0003e3fff 
000000c000225120:  000000c000225130  00007fff2059dd7d 
000000c000225130:  000000c0002256e0  0000000000000000 
000000c000225140:  000000000515ffe0  000000c000225258 
000000c000225150:  000000c0002253c8  00000000000000de 
000000c000225160:  00007f9139711000  0000000000000080 
000000c000225170:  0000000000002060  000000c0003c6000 
000000c000225180:  0000000000005fff  000000c0003dbf20 
000000c000225190:  000000c0003c3f20  000000c0002256e0 
000000c0002251a0:  000000c000225680  0000000000000000 
000000c0002251b0:  0000000000000000  000000c0003c6000 
000000c0002251c0:  0000000000000020  000000000000000e 
000000c0002251d0:  0000000000000009  000080c0003c6000 
000000c0002251e0:  000080c0003e3fff  0000000004075ac7 <runtime.memmove+1063> 
runtime.throw(0x522e8ce, 0x39)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigNotOnStack(0x10)
	/usr/local/go/src/runtime/signal_unix.go:918 +0x85
runtime.adjustSignalStack(0xc000000010, 0xc00005a900, 0xc000225090, 0x0)
	/usr/local/go/src/runtime/signal_unix.go:509 +0x285
runtime.sigtrampgo(0xc000000010, 0xc000225560, 0xc0002255c8)
	/usr/local/go/src/runtime/signal_unix.go:449 +0x171
runtime: unexpected return pc for runtime.sigtramp called from 0xc000225560
stack: frame={sp:0xc0002250e0, fp:0xc0002250f0} stack=[0xc00021d010,0xc000225410)
000000c000224fe0:  000000c000225000  0000000004052ec5 <runtime.sigNotOnStack+133> 
000000c000224ff0:  000000000522e8ce  0000000000000039 
000000c000225000:  000000c000225058  0000000004051ea5 <runtime.adjustSignalStack+645> 
000000c000225010:  0000000000000010  000000c000225040 
000000c000225020:  000000c000225068  0000000000000018 
000000c000225030:  0100000000000018  000000000514c8c0 
000000c000225040:  000000000e765000  0000000000010000 
000000c000225050:  0000000000000001  000000c0002250d0 
000000c000225060:  0000000004051b11 <runtime.sigtrampgo+369>  000000c000000010 
000000c000225070:  000000c00005a900  000000c000225090 
000000c000225080:  0000000000000000  000000c000100900 
000000c000225090:  0000000000000000  0000000000000000 
000000c0002250a0:  0000000000000000  0000000000000000 
000000c0002250b0:  0000000000000000  000000c00021aa80 
000000c0002250c0:  000000c000225560  000000c0002255c8 
000000c0002250d0:  000000c000225120  0000000004076233 <runtime.sigtramp+51> 
000000c0002250e0: <000000c000000010 !000000c000225560 
000000c0002250f0: >000000c0002255c8  000000c0002255c8 
000000c000225100:  ba5cb4a606f300ac  0000000000000009 
000000c000225110:  000080c0003c6000  000080c0003e3fff 
000000c000225120:  000000c000225130  00007fff2059dd7d 
000000c000225130:  000000c0002256e0  0000000000000000 
000000c000225140:  000000000515ffe0  000000c000225258 
000000c000225150:  000000c0002253c8  00000000000000de 
000000c000225160:  00007f9139711000  0000000000000080 
000000c000225170:  0000000000002060  000000c0003c6000 
000000c000225180:  0000000000005fff  000000c0003dbf20 
000000c000225190:  000000c0003c3f20  000000c0002256e0 
000000c0002251a0:  000000c000225680  0000000000000000 
000000c0002251b0:  0000000000000000  000000c0003c6000 
000000c0002251c0:  0000000000000020  000000000000000e 
000000c0002251d0:  0000000000000009  000080c0003c6000 
000000c0002251e0:  000080c0003e3fff  0000000004075ac7 <runtime.memmove+1063> 
runtime.sigtramp(0xc0002255c8, 0xc0002255c8, 0xba5cb4a606f300ac, 0x9, 0x80c0003c6000, 0x80c0003e3fff, 0xc000225130, 0x7fff2059dd7d, 0xc0002256e0, 0x0, ...)
	/usr/local/go/src/runtime/sys_darwin_amd64.s:234 +0x33
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x40748c1
goroutine 1 [chan receive]:
testing.(*T).Run(0xc00021a600, 0x52132e2, 0x7, 0x523a0f8, 0x40936e6)
	/usr/local/go/src/testing/testing.go:1240 +0x2da
testing.runTests.func1(0xc00021a480)
	/usr/local/go/src/testing/testing.go:1512 +0x78
testing.tRunner(0xc00021a480, 0xc00031fde0)
	/usr/local/go/src/testing/testing.go:1194 +0xef
testing.runTests(0xc000229830, 0x57f68e0, 0x2, 0x2, 0xc0041190aeb92a98, 0x8bb307796e, 0x5805960, 0x521620b)
	/usr/local/go/src/testing/testing.go:1510 +0x2fe
testing.(*M).Run(0xc000278580, 0x0)
	/usr/local/go/src/testing/testing.go:1418 +0x1eb
main.main()
	_testmain.go:61 +0x138
goroutine 19 [chan receive]:
testing.(*T).Run(0xc00021b500, 0x5225b4d, 0x25, 0xc0001ce740, 0x64fff01)
	/usr/local/go/src/testing/testing.go:1240 +0x2da
github.com/open-policy-agent/opa/internal/wasm/sdk/opa_test.TestOPA(0xc00021a600)
	/Users/jlarsson-local/github/opa/internal/wasm/sdk/opa/opa_test.go:235 +0x78d
testing.tRunner(0xc00021a600, 0x523a0f8)
	/usr/local/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
goroutine 55 [running]:
	goroutine running on other thread; stack unavailable
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
```

## Steps to Reproduce the Problem

```
rm -rf opa/
git clone https://github.com/open-policy-agent/opa.git
Cloning into 'opa'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 43470 (delta 0), reused 0 (delta 0), pack-reused 43469
Receiving objects: 100% (43470/43470), 131.09 MiB | 20.36 MiB/s, done.
Resolving deltas: 100% (23369/23369), done.
Updating files: 100% (5329/5329), done.
go clean -testcache                                   
cd opa
make test
```

**Comment by tsandall** [comment]
@johanneslarsson thanks for filing this. You can skip the wasm-related tests by setting `WASM_ENABLED=0` when running make (e.g., `make wasm WASM_ENABLED=0`). All that does is remove the `-tags=opa_wasm` flag from the `go` commands executed by the makefile. That will disable any code paths that rely on the wasm runtime.

**Comment by johanneslarsson** [comment]
@tsandall Thanks, it helps to disable it when working a PR. 

I reproduced it in two different go versions:
`go version go1.16 darwin/amd64`
`go version go1.15.5 darwin/amd64`

**Comment by tsandall** [comment]
I've found an issue w/ the wasm runtime and reported it upstream (https://github.com/bytecodealliance/wasmtime-go/issues/60). It affects how we handle runtime errors like assignment conflicts.

**Comment by johanneslarsson** [comment]
Thanks for a quick resolution!
