### ISSUE TITLE
encountered panic in metrics reporting 

### ISSUE THREAD

**Issue by brumer** [open-policy-agent/opa#3368]
While going through OPA logs I encountered a panic, unfortunately, I do not know how to reproduce the issue.

* Version v0.25.1
* Running in server mod as a Kubernetes pod with discovery configuration and status reporting

`	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7abe3d]

goroutine 163 [running]:
encoding/json.(*encodeState).marshal.func1(0xc0006973d8)
	/usr/local/go/src/encoding/json/encode.go:328 +0x8d
panic(0xcc12a0, 0x1375cc0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/open-policy-agent/opa/metrics.(*metrics).All(0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/open-policy-agent/opa@v0.25.1/metrics/metrics.go:142 +0x5d
github.com/open-policy-agent/opa/metrics.(*metrics).MarshalJSON(0x0, 0xd4fce0, 0x0, 0x7f41484f41d8, 0x0, 0x1)
	/home/circleci/go/pkg/mod/github.com/open-policy-agent/opa@v0.25.1/metrics/metrics.go:104 +0x2b
encoding/json.marshalerEncoder(0xc000796000, 0xd0d780, 0xc001126738, 0x194, 0x100)
	/usr/local/go/src/encoding/json/encode.go:479 +0xad
encoding/json.structEncoder.encode(0xc000257b00, 0xa, 0x10, 0xc0000fc1b0, 0xc000796000, 0xd82200, 0xc001126680, 0x199, 0xc000430100)
	/usr/local/go/src/encoding/json/encode.go:761 +0x2ab
encoding/json.ptrEncoder.encode(0xc0000fc1e0, 0xc000796000, 0xcf5580, 0xc001126680, 0x16, 0x100)
	/usr/local/go/src/encoding/json/encode.go:944 +0x125
encoding/json.mapEncoder.encode(0xc000421bb0, 0xc000796000, 0xcb9d00, 0xc00045a2e0, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:813 +0x366
encoding/json.structEncoder.encode(0xc000436480, 0x6, 0x8, 0xc0000fc2a0, 0xc000796000, 0xd5d740, 0xc00045a2d0, 0x199, 0xcb0100)
	/usr/local/go/src/encoding/json/encode.go:761 +0x2ab
encoding/json.ptrEncoder.encode(0xc0000fc2d0, 0xc000796000, 0xc59340, 0xc00045a2d0, 0x16, 0xc50100)
	/usr/local/go/src/encoding/json/encode.go:944 +0x125
encoding/json.(*encodeState).reflectValue(0xc000796000, 0xc59340, 0xc00045a2d0, 0x16, 0xc000690100)
	/usr/local/go/src/encoding/json/encode.go:360 +0x82
encoding/json.(*encodeState).marshal(0xc000796000, 0xc59340, 0xc00045a2d0, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:332 +0xf9
encoding/json.(*Encoder).Encode(0xc000697618, 0xc59340, 0xc00045a2d0, 0x1, 0xc0001e01d1)
	/usr/local/go/src/encoding/json/stream.go:206 +0x8b
github.com/open-policy-agent/opa/plugins/rest.Client.Do(0x0, 0xc000138d90, 0xc000049a90, 0x8, 0xc00043c090, 0x2a, 0x0, 0x0, 0xc000049b10, 0x0, ...)
	/home/circleci/go/pkg/mod/github.com/open-policy-agent/opa@v0.25.1/plugins/rest/rest.go:191 +0xffd
github.com/open-policy-agent/opa/plugins/status.(*Plugin).oneShot(0xc00047e1b0, 0xece058, 0xc000416d80, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/open-policy-agent/opa@v0.25.1/plugins/status/plugin.go:272 +0x425
github.com/open-policy-agent/opa/plugins/status.(*Plugin).loop(0xc00047e1b0)
	/home/circleci/go/pkg/mod/github.com/open-policy-agent/opa@v0.25.1/plugins/status/plugin.go:214 +0x268
created by github.com/open-policy-agent/opa/plugins/status.(*Plugin).Start
	/home/circleci/go/pkg/mod/github.com/open-policy-agent/opa@v0.25.1/plugins/status/plugin.go:149 +0x77
`

**Comment by ashutosh-narkar** [comment]
Can you provide the boot config and service config ? Also it would be helpful if you could share any other relevant info to reproduce this or the actions that led to this.

**Comment by anderseknert** [comment]
Closing due to inactivity.
