### ISSUE TITLE
opa fmt panics with future keyword import every, in, and comment

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4606]
```rego
package test

#
import future.keywords.every

p {
    1 in []
}
```

importing `every` implies importing `in`, it's probably related to that.

`opa fmt f.rego` gives this 💥 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x44c7840]

goroutine 1 [running]:
github.com/open-policy-agent/opa/format.mapImportsToComments(...)
        /Users/stephan/Sources/open-policy-agent/opa/format/format.go:963
github.com/open-policy-agent/opa/format.(*writer).writeImports(0xc000301260, {0xc000700c70, 0x2, 0x2}, {0xc000312318, 0x1, 0xc000311068?})
        /Users/stephan/Sources/open-policy-agent/opa/format/format.go:817 +0x540
github.com/open-policy-agent/opa/format.(*writer).writeModule(0xc000301260, 0x1?)
        /Users/stephan/Sources/open-policy-agent/opa/format/format.go:213 +0x367
github.com/open-policy-agent/opa/format.Ast({0x55fb440?, 0xc000322580?})
        /Users/stephan/Sources/open-policy-agent/opa/format/format.go:99 +0x5dc
github.com/open-policy-agent/opa/format.Source({0x7ff7bfeff777, 0x6}, {0xc00014e200?, 0x0?, 0x7188080?})
        /Users/stephan/Sources/open-policy-agent/opa/format/format.go:30 +0x98
github.com/open-policy-agent/opa/cmd.formatFile(0x6151b68, {0x587d2e0, 0xc00012e008}, {0x7ff7bfeff777, 0x6}, {0x5887d98, 0xc0002225b0}, {0x0?, 0x0?})
        /Users/stephan/Sources/open-policy-agent/opa/cmd/fmt.go:112 +0x285
github.com/open-policy-agent/opa/cmd.opaFmt.func1({0x7ff7bfeff777?, 0x40bad86?}, {0x5887d98?, 0xc0002225b0?}, {0x0?, 0x0?})
        /Users/stephan/Sources/open-policy-agent/opa/cmd/fmt.go:77 +0x5f
path/filepath.walk({0x7ff7bfeff777, 0x6}, {0x5887d98, 0xc0002225b0}, 0x5747788)
        /usr/local/go/src/path/filepath/path.go:418 +0x123
path/filepath.Walk({0x7ff7bfeff777, 0x6}, 0x5747788)
        /usr/local/go/src/path/filepath/path.go:505 +0x6c
github.com/open-policy-agent/opa/cmd.opaFmt({0xc00035aa00?, 0x1, 0x0?})
        /Users/stephan/Sources/open-policy-agent/opa/cmd/fmt.go:76 +0xdf
github.com/open-policy-agent/opa/cmd.glob..func3(0x6102bc0?, {0xc00035aa00?, 0x2?, 0x2?})
        /Users/stephan/Sources/open-policy-agent/opa/cmd/fmt.go:54 +0x27
github.com/spf13/cobra.(*Command).execute(0x6102bc0, {0xc00035a9e0, 0x2, 0x2})
        /Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x6102940)
        /Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:902
main.main()
        /Users/stephan/Sources/open-policy-agent/opa/main.go:15 +0x25
```

**Comment by srenatus** [comment]
Found via https://github.com/open-policy-agent/opa/pull/4604
