### ISSUE TITLE
Using entrypoint annotation with --optimize 2 may cause panic

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#5368]
While reporting https://github.com/open-policy-agent/opa/issues/5367, I decided to try and skip the `-e` flag in favor of the new entrypoint annotation. This worked for `--optimization 1`, but caused a panic with `--optimization 2`. To reproduce, simply use the same policy and input as used in that issue, but replace the `-e` flag with an annotation over the `main` rule.

Result of policy evaluation is now:

```shell
$ opa eval -f pretty -d policy.rego -i input.json --optimize 1 data.system.main
false
```

```shell
$ opa eval -f pretty -d policy.rego -i input.json --optimize 2 data.system.main
panic: interface conversion: ast.Node is nil, not *ast.Rule [recovered]
	panic: interface conversion: ast.Node is nil, not *ast.Rule

goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.(*Compiler).compile.func1()
	/Users/anderseknert/git/opa/opa/ast/compile.go:1350 +0x5c
panic({0x101d29180, 0x1400001b680})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:884 +0x204
github.com/open-policy-agent/opa/ast.(*AnnotationSet).add(0x1400001b5f0, 0x140001a4180)
	/Users/anderseknert/git/opa/opa/ast/annotations.go:604 +0x2f0
github.com/open-policy-agent/opa/ast.BuildAnnotationSet({0x140001f39a0, 0x2, 0x2})
	/Users/anderseknert/git/opa/opa/ast/annotations.go:589 +0x1e4
github.com/open-policy-agent/opa/ast.(*Compiler).setAnnotationSet(0x1400071a140)
	/Users/anderseknert/git/opa/opa/ast/compile.go:1289 +0x88
github.com/open-policy-agent/opa/ast.(*Compiler).runStage(0x1?, {0x10186098f?, 0x10184f42f?}, 0x13?)
	/Users/anderseknert/git/opa/opa/ast/compile.go:1335 +0xbc
github.com/open-policy-agent/opa/ast.(*Compiler).compile(0x1400071a140)
	/Users/anderseknert/git/opa/opa/ast/compile.go:1355 +0xb4
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0x1400071a140, 0x1400063dda0)
	/Users/anderseknert/git/opa/opa/ast/compile.go:447 +0x36c
github.com/open-policy-agent/opa/bundle.compileModules(0x1400071a140, {0x101e8f100, 0x1400040c080}, 0x1400045c0a0?, 0x101e80040?, 0x0)
	/Users/anderseknert/git/opa/opa/bundle/store.go:788 +0x2bc
github.com/open-policy-agent/opa/bundle.activateBundles(0x1400063e750)
	/Users/anderseknert/git/opa/opa/bundle/store.go:453 +0x5e0
github.com/open-policy-agent/opa/bundle.Activate(...)
	/Users/anderseknert/git/opa/opa/bundle/store.go:310
github.com/open-policy-agent/opa/rego.(*Rego).compileModules(0x1400036e900, {0x101e8a3f0, 0x14000124008}, {0x101e80040, 0x140004365d0}, {0x101e8f100, 0x1400040c080})
	/Users/anderseknert/git/opa/opa/rego/rego.go:1832 +0x15c
github.com/open-policy-agent/opa/rego.(*Rego).prepare(0x1400036e900, {0x101e8a3f0, 0x14000124008}, 0x100e1de4c?, {0x1400063e9c0, 0x1, 0x1})
	/Users/anderseknert/git/opa/opa/rego/rego.go:1635 +0x110
github.com/open-policy-agent/opa/rego.(*Rego).PrepareForEval(0x1400036e900, {0x101e8a3f0, 0x14000124008}, {0x0, 0x0, 0x4d1d00?})
	/Users/anderseknert/git/opa/opa/rego/rego.go:1503 +0x398
github.com/open-policy-agent/opa/cmd.evalOnce({0x101e8a3f0, 0x14000124008}, 0x140001fc000)
	/Users/anderseknert/git/opa/opa/cmd/eval.go:421 +0x1ac
github.com/open-policy-agent/opa/cmd.eval({_, _, _}, {0x1400000ec78, 0x0, 0x0, {0x140002763b0, 0x1, 0x1}, {0x1026c8028, ...}, ...}, ...)
	/Users/anderseknert/git/opa/opa/cmd/eval.go:349 +0x314
github.com/open-policy-agent/opa/cmd.init.5.func2(0x140001a9500?, {0x140000b0630?, 0x9?, 0x9?})
	/Users/anderseknert/git/opa/opa/cmd/eval.go:271 +0x68
github.com/spf13/cobra.(*Command).execute(0x140001a9500, {0x140000b05a0, 0x9, 0x9})
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x102673620)
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/anderseknert/git/opa/opa/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/Users/anderseknert/git/opa/opa/main.go:14 +0x28
```

Is the annotation optimized away before use, perhaps?

**Comment by srenatus** [comment]
Curious, this one. Because as far as I remember, the only difference between level 1 and 2 is shallow inlining:
https://sourcegraph.com/github.com/open-policy-agent/opa@afe58b45be012216083f1f150d3c1dfbb66ad17f/-/blob/compile/compile.go?L480

But I haven't had a closer look yet.

**Comment by philipaconrad** [comment]
Indeed. Changing the `1` in `WithShallowInlining(c.optimizationLevel <= 1)` to a `2` results in panics disappearing until `--optimize 3` is provided. Something about shallow inlining **not** happening is important there.

**Comment by philipaconrad** [comment]
The reason the shallow inlining breaks stuff is because in `ast/query.go`'s `(*Query) PartialRun` method, online L401-L403, there's logic that applies copy propagation *only when shallow inlining is disabled*.

The copy propagation seems to rip the `Node` structures out from under the annotation, and this results in a panic blowing everything up during compilation.
