### ISSUE TITLE
Crash in `opa build` on 0.47.0 - regression from v0.46.3

### ISSUE THREAD

**Issue by benweint** [open-policy-agent/opa#5479]
## Short description 

I have an existing CI pipeline where we're building OPA bundles using `opa build`, and I noticed that it reliably crashes with my bundle in v0.47.0, but didn't in v0.46.3 and earlier versions. 

Here's the full command I'm invoking and the crashing backtrace:

```
❯ opa version                                   
Version: 0.47.0
Build Commit: 09019bea950a755d7bb3925d22917b3b62203f3a
Build Timestamp: 2022-12-05T09:03:26Z
Build Hostname: Mac-1670231591794.local
Go Version: go1.19.3
Platform: darwin/arm64
WebAssembly: unavailable

❯ opa build \
                --ignore '*_test.rego' \
                --optimize 1 \
                --entrypoint envoy/authz/allow \
                bundle
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x100fd2ce4]

goroutine 1 [running]:
github.com/open-policy-agent/opa/format.groupIterable({0x14000358c80, 0x3, 0x4}, 0x14000173980)
	/Users/runner/work/opa/opa/format/format.go:1026 +0x2c4
github.com/open-policy-agent/opa/format.(*writer).writeIterable(0x140003715c0, {0x14000358c80?, 0x14000814ea8?, 0x0?}, 0x14000814e98?, 0x1009a22d0?, {0x0, 0x0, 0x0}, 0x0?)
	/Users/runner/work/opa/opa/format/format.go:928 +0x4c
github.com/open-policy-agent/opa/format.(*writer).writeObject(0x140003715c0, {0x101a3a180, 0x1400036d6e0}, 0x100203d20?, {0x0, 0x0, 0x0})
	/Users/runner/work/opa/opa/format/format.go:799 +0x150
github.com/open-policy-agent/opa/format.(*writer).writeTermParens(0x140003715c0, 0xae?, 0x140001714b8, {0x0?, 0x14000815008?, 0x1009a47dc?})
	/Users/runner/work/opa/opa/format/format.go:666 +0x454
github.com/open-policy-agent/opa/format.(*writer).writeTerm(...)
	/Users/runner/work/opa/opa/format/format.go:653
github.com/open-policy-agent/opa/format.(*writer).writeHead(0x140003715c0?, 0x14000371200?, 0x0?, 0x0?, 0x0?, 0x0?, {0x0?, 0x0?, 0x0?})
	/Users/runner/work/opa/opa/format/format.go:462 +0x3c4
github.com/open-policy-agent/opa/format.(*writer).writeRule(0x140003715c0, 0x1400049d440, 0x0?, 0x0, 0x0, {0x0, 0x0, 0x0})
	/Users/runner/work/opa/opa/format/format.go:314 +0x1fc
github.com/open-policy-agent/opa/format.(*writer).writeRules(0x101992fa0?, {0x14000166800, 0x1a, 0x1?}, 0x0?, 0x0?, {0x0?, 0x102704108?, 0x8?})
	/Users/runner/work/opa/opa/format/format.go:289 +0x7c
github.com/open-policy-agent/opa/format.(*writer).writeModule(0x140003715c0, 0x0?, 0x0?, 0x0?)
	/Users/runner/work/opa/opa/format/format.go:256 +0x190
github.com/open-policy-agent/opa/format.AstWithOpts({0x10193d9a0?, 0x14000344280?}, {0x80?})
	/Users/runner/work/opa/opa/format/format.go:135 +0x58c
github.com/open-policy-agent/opa/format.Ast(...)
	/Users/runner/work/opa/opa/format/format.go:61
github.com/open-policy-agent/opa/bundle.(*Bundle).FormatModules(0x1400009cc60, 0x0)
	/Users/runner/work/opa/opa/bundle/bundle.go:957 +0xec
github.com/open-policy-agent/opa/compile.(*Compiler).Build(0x14000815b10, {0x101a2f290, 0x1400019e008})
	/Users/runner/work/opa/opa/compile/compile.go:336 +0x330
github.com/open-policy-agent/opa/cmd.dobuild({0x1400000cf78, 0x1400025fe30, 0x0, 0x0, 0x1, {{0x1400047d420, 0x1, 0x1}, 0x1}, {0x16f467052, ...}, ...}, ...)
	/Users/runner/work/opa/opa/cmd/build.go:309 +0x6c8
github.com/open-policy-agent/opa/cmd.init.1.func2(0x14000274900?, {0x1400002c4d0?, 0xb?, 0xb?})
	/Users/runner/work/opa/opa/cmd/build.go:220 +0x50
github.com/spf13/cobra.(*Command).execute(0x14000274900, {0x1400002c420, 0xb, 0xb})
	/Users/runner/work/opa/opa/vendor/github.com/spf13/cobra/command.go:920 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x10221fcc0)
	/Users/runner/work/opa/opa/vendor/github.com/spf13/cobra/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/work/opa/opa/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/Users/runner/work/opa/opa/main.go:14 +0x28
``` 

## Reduced test case

I've reduced this down to the following test case, consisting of two files:

```
❯ tree bundle 
bundle
└── envoy
    ├── authz.rego
    └── data.yaml

1 directory, 2 files

❯ cat bundle/envoy/authz.rego
package envoy.authz

foo := data.envoy.foo
result {
    foo[input.baz]
}

❯ cat bundle/envoy/data.yaml 
foo:
  bar: true

❯ opa build --optimize 1 --entrypoint envoy/authz/result bundle  
panic: runtime error: invalid memory address or nil pointer dereference
< ... snip ... >
```

Note that changing `authz.rego` to look like this:

```
package envoy.authz

result {
    data.envoy.foo[input.baz]
}
```

... makes the problem disappear. 

## Expected behavior

I would not expect `opa build` to crash. It should either build the bundle, or emit a useful error (as it did in <= 0.46.3).

## Actual behavior

`opa build` crashes when given this input.

**Comment by srenatus** [comment]
Thanks for reporting. We'll get it fixed 🤞

**Comment by srenatus** [comment]
📝 git bisect tells me #5380

**Comment by srenatus** [comment]
So it seems we've got lazy objects in the PE result, and they get forced _after_ the formatter has filled in default locations. So the forced ast.Object we get will not have the default location, and accessing `.Location.Row` then explodes.

**Comment by srenatus** [comment]
Turns out the visitor turned a blind eye on LazyObject.
