### ISSUE TITLE
opa build: combine -Ox with -t wasm

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#5548]
Optimizations, i.e. running partial eval, before compiling into Wasm is something you could want to do. However, at the moment, the only way to get that done is to do a series of calls:

```
$ opa build -O2 -o o2.tar.gz -e x/y x.rego
$ opa build  -t wasm -e x/y -b o2.tar.gz    
$ opa eval -fpretty -b bundle.tar.gz data.x.y
true
```
and the resulting bundle looks a bit funny:
```
$ tar tvf bundle.tar.gz                      
-rw-------  0 0      0           3 Jan  1  1970 /data.json
-rw-------  0 0      0          27 Jan  1  1970 /o2.tar.gz/optimized/x.rego
-rw-------  0 0      0      131444 Jan  1  1970 /policy.wasm
-rw-------  0 0      0          83 Jan  1  1970 /.manifest
```

It would be nice if you could just call `opa build -O2 -t wasm -e x/y x.rego` to get the steps combined.

If you run this command now, it'll panic:
```
$ opa build -O2 -t wasm -e x/y x.rego     
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).fileAddr(...)
        /Users/stephan/Sources/open-policy-agent/opa/internal/compiler/wasm/wasm.go:1662
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).runtimeErrorAbort(0x1016d0800, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}}, 0xc00063f028?)
        /Users/stephan/Sources/open-policy-agent/opa/internal/compiler/wasm/wasm.go:1754 +0x2b3
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).compileBlock(0xc0003dd200, 0xc0002454d0?)
        /Users/stephan/Sources/open-policy-agent/opa/internal/compiler/wasm/wasm.go:1047 +0x805
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).compileFunc(0xc0003dd200, 0xc0000b4cc0)
        /Users/stephan/Sources/open-policy-agent/opa/internal/compiler/wasm/wasm.go:855 +0x85e
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).compileFuncs(0xc0003dd200)
        /Users/stephan/Sources/open-policy-agent/opa/internal/compiler/wasm/wasm.go:717 +0x85
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).Compile(0xc0003dd200)
        /Users/stephan/Sources/open-policy-agent/opa/internal/compiler/wasm/wasm.go:311 +0x58
github.com/open-policy-agent/opa/compile.(*Compiler).compileWasm(0xc00063fb30, {0x101c2ecb0, 0xc000124008})
        /Users/stephan/Sources/open-policy-agent/opa/compile/compile.go:627 +0x2b0
github.com/open-policy-agent/opa/compile.(*Compiler).Build(0xc00063fb30, {0x101c2ecb0, 0xc000124008})
        /Users/stephan/Sources/open-policy-agent/opa/compile/compile.go:307 +0x1cb
github.com/open-policy-agent/opa/cmd.dobuild({0xc0001eb4d0, 0xc0000d6cc0, 0x0, 0x0, 0x2, {{0xc00043a100, 0x1, 0x1}, 0x1}, {0x10184bb09, ...}, ...}, ...)
        /Users/stephan/Sources/open-policy-agent/opa/cmd/build.go:313 +0x888
github.com/open-policy-agent/opa/cmd.init.1.func2(0xc0001fc900?, {0xc0000b41e0?, 0x6?, 0x6?})
        /Users/stephan/Sources/open-policy-agent/opa/cmd/build.go:220 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0001fc900, {0xc0000b4180, 0x6, 0x6})
        /Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1025d8040)
        /Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:968
main.main()
        /Users/stephan/Sources/open-policy-agent/opa/main.go:14 +0x25
```

**Comment by srenatus** [comment]
I'm on the fence wrt `good-first-issue`. I thought it was just about some code flow changes in `compile/compile.go`, but it probably is a bit more involved: when feeding the output of the optimizer (i.e. PE) into the wasm compiler, we don't have locations on all AST nodes. I think that's what blows up here.

**Comment by Sdssourcing** [comment]
#

**Comment by nikpivkin** [comment]
Hi @srenatus !

The workaround with calling multiple commands does not work if entry point annotations are used instead of flags.

**Comment by lopter** [comment]
I just ran into that issue, it's a little confusing.

Edit: after some more testing it looks like referencing input makes the crash go away.

This works:

```
$ cat test.rego
package com.example.policy

default allow := false

# METADATA
# entrypoint: true
allow := true if {
    match_all := -1
    matches = regex.find_n("^(to)+$", input.value, match_all)

    count(matches) > 0
}

$ opa build -t wasm -O3 test.rego
```

This crashes:

```
$ cat base.rego
package com.example.policy

# METADATA
# entrypoint: true
allow := true

$ opa build -t wasm -O3 base.rego
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).fileAddr(...)
	github.com/open-policy-agent/opa/internal/compiler/wasm/wasm.go:1665
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).runtimeErrorAbort(0x1019bebe0?, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}}, 0x140003cee68?)
	github.com/open-policy-agent/opa/internal/compiler/wasm/wasm.go:1757 +0x270
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).compileBlock(0x14000151560, 0x140003cf3c8?)
	github.com/open-policy-agent/opa/internal/compiler/wasm/wasm.go:1054 +0x27b4
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).compileFunc(0x14000151560, 0x14000111f20)
	github.com/open-policy-agent/opa/internal/compiler/wasm/wasm.go:856 +0x730
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).compileFuncs(0x14000151560)
	github.com/open-policy-agent/opa/internal/compiler/wasm/wasm.go:718 +0x6c
github.com/open-policy-agent/opa/internal/compiler/wasm.(*Compiler).Compile(0x14000151560)
	github.com/open-policy-agent/opa/internal/compiler/wasm/wasm.go:312 +0x60
github.com/open-policy-agent/opa/v1/compile.(*Compiler).compileWasm(0x1400012f400, {0x101b64178, 0x102554100})
	github.com/open-policy-agent/opa/v1/compile/compile.go:716 +0x188
github.com/open-policy-agent/opa/v1/compile.(*Compiler).Build(0x1400012f400, {0x101b64178, 0x102554100})
	github.com/open-policy-agent/opa/v1/compile/compile.go:354 +0x184
github.com/open-policy-agent/opa/cmd.dobuild({0x1400013e600, 0x14000179140, 0x0, 0x0, 0x3, {{0x0, 0x0, 0x0}, 0x0}, {0x1012b1b63, ...}, ...}, ...)
	github.com/open-policy-agent/opa/cmd/build.go:348 +0x868
github.com/open-policy-agent/opa/cmd.init.1.func2(0x14000138c00?, {0x14000142a40?, 0x4?, 0x1012a76c4?})
	github.com/open-policy-agent/opa/cmd/build.go:241 +0x50
github.com/spf13/cobra.(*Command).execute(0x14000440308, {0x14000142a00, 0x4, 0x4})
	github.com/spf13/cobra@v1.9.1/command.go:1019 +0x82c
github.com/spf13/cobra.(*Command).ExecuteC(0x10250f9a0)
	github.com/spf13/cobra@v1.9.1/command.go:1148 +0x384
github.com/spf13/cobra.(*Command).Execute(0x1023dfe68?)
	github.com/spf13/cobra@v1.9.1/command.go:1071 +0x1c
main.main()
	github.com/open-policy-agent/opa/main.go:14 +0x24
$
```

---

```
$ opa version
Version: 1.5.1
Build Commit:
Build Timestamp:
Build Hostname:
Go Version: go1.24.4
Platform: darwin/arm64
Rego Version: v1
WebAssembly: unavailable

$
```

**Comment by srenatus** [comment]
@lopter Have you tried without -O3? From the original issue, I'd think any `-O` shouldn't make a difference combined with `-twasm`. If it happens without `-O`, please open another issue 😅

**Comment by lopter** [comment]
This only happens with (any) `-O`, and when `input` is not referenced (as shown above). Maybe referencing something else than `input` also avoids triggering this bug, I haven't tried. It works in all cases without `-O`.
