### ISSUE TITLE
Panic calling platform.aws.sign_req

### ISSUE THREAD

**Issue by subnova** [open-policy-agent/opa#5841]
## Short description 

The `platform.aws.sign_req` built in function always panics due to use of an unintialized map at https://github.com/open-policy-agent/opa/blob/main/topdown/providers.go#L56

Examples:

* OPA version
v0.50.1

* Example query, input, data, and policy that OPA was given
```rego
package sign

req := {
  "method": "post",
  "url": "https://sts.amazonaws.com/",
  "headers": {
    "accept-encoding": "identity",
    "content-type": "application/x-www-form-urlencoded",
  },
  "raw_body": "Action=GetCallerIdentity&Version=2011-06-15",
}

aws_config := {
  "aws_access_key": "REDACTED",
  "aws_secret_access_key": "REDACTED",
  "aws_session_token": "REDACTED",
  "aws_service": "sts",
  "aws_region": "eu-west-2",
}

signed_req := providers.aws.sign_req(req, aws_config, time.now_ns())
```

```rego
package sign

import future.keywords

test_sign if {
  signed_req
}
```

* Example output that OPA returned
```
panic: assignment to entry in nil map

goroutine 10 [running]:
github.com/open-policy-agent/opa/topdown.objectToMap.func1(0x100499320?, 0xc000180f80?)
	/Users/runner/work/opa/opa/topdown/providers.go:60 +0xc5
github.com/open-policy-agent/opa/ast.(*object).Foreach.func1(0x103616f48?, 0x10316cd28?)
	/Users/runner/work/opa/opa/ast/term.go:2188 +0x1d
github.com/open-policy-agent/opa/ast.(*object).Iter(0x100011747?, 0xc00074b558)
	/Users/runner/work/opa/opa/ast/term.go:2165 +0x62
github.com/open-policy-agent/opa/ast.(*object).Foreach(0xc00045c930?, 0x2b?)
	/Users/runner/work/opa/opa/ast/term.go:2187 +0x35
github.com/open-policy-agent/opa/topdown.objectToMap({0x101c5eda0, 0xc000180f80})
	/Users/runner/work/opa/opa/topdown/providers.go:57 +0x4f
github.com/open-policy-agent/opa/topdown.builtinAWSSigV4SignReq({{0x101c52fa8, 0xc000710030}, {0x101c57b80, 0xc000716040}, {0x101c47cc0, 0xc000142080}, 0xc000711050, {0x101c4d520, 0xc0004b8098}, 0xc0002b21e0, ...}, ...)
```

## Steps To Reproduce
1. Obtain AWS credentials and substitute into the source code
2. Run the test

**Comment by ashutosh-narkar** [comment]
Thanks for reporting this. Looks like this happens when `headers` are present in the request. We should also add test coverage for this case in [here](https://github.com/open-policy-agent/opa/blob/main/test/cases/testdata/providers-aws/aws-sign_req.yaml). We'll push a fix soon.
