### ISSUE TITLE
OPA process fails with "fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by alex0z1** [open-policy-agent/opa#6172]
We have an issue with the 0.54 version. We use kube-mgmt to load policies into OPA and multiple kube-mgmt/opa pod replicas. When kube-mgmt loads policies into its own opa container, it updates configmaps with annotation about policy status, and it makes another kube-mgmt replica to load policies again, and the same repeats for other replicas. So as a result, we have too many updates in OPA at the same time. We applied a workaround by implementing a startupProve for kube-mgmt that slows down restarts, and this significantly reduces the chances of opa failure since we have fewer policy changes at the same time.

Here is an error from opa logs when a process dies

```
fatal error: concurrent map writes

goroutine 182 [running]:
github.com/open-policy-agent/opa/ast.(*Compiler).rewriteLocalVarsInRule(0xc0001a4500, 0xc0013c3d10, 0xc000a96480?, 0xc0013c3d10?, 0xc000e4ffc0)
	/src/ast/compile.go:2299 +0x8e5
github.com/open-policy-agent/opa/ast.(*Compiler).rewriteLocalVars.func1(0xc0013c3d10)
	/src/ast/compile.go:2222 +0x30b
github.com/open-policy-agent/opa/ast.WalkRules.func1({0x1da20c0?, 0xc0013c3d10?})
	/src/ast/visit.go:245 +0x42
github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk(0xc000677890, {0x1da20c0?, 0xc0013c3d10?})
	/src/ast/visit.go:286 +0x5f
github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk(0xc000677890, {0x1d29ba0?, 0xc001505800?})
	/src/ast/visit.go:297 +0xd6a
github.com/open-policy-agent/opa/ast.WalkRules({0x1d29ba0, 0xc001505800}, 0xc0005cdb78)
	/src/ast/visit.go:254 +0x9a
github.com/open-policy-agent/opa/ast.(*Compiler).rewriteLocalVars(0xc0001a4500)
	/src/ast/compile.go:2207 +0x48
github.com/open-policy-agent/opa/ast.(*Compiler).runStage(0x2296490?, {0x1e36dbf?, 0x1e19bb7?}, 0xb?)
	/src/ast/compile.go:1383 +0xec
github.com/open-policy-agent/opa/ast.(*Compiler).compile(0xc0001a4500)
	/src/ast/compile.go:1403 +0xd8
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc0001a4500, 0xc0008d4040)
	/src/ast/compile.go:457 +0x3b5
github.com/open-policy-agent/opa/bundle.compileModules(0xc0001a4500, {0x229da80, 0xc0013bc1e0}, 0x2a?, 0x228e9e0?, 0x0)
	/src/bundle/store.go:788 +0x3a5
github.com/open-policy-agent/opa/bundle.activateBundles(0xc0008d49d8)
	/src/bundle/store.go:453 +0x78b
github.com/open-policy-agent/opa/bundle.Activate(...)
	/src/bundle/store.go:310
github.com/open-policy-agent/opa/rego.(*Rego).compileModules(0xc0010ca700, {0x22990e0, 0xc000eea1b0}, {0x228e9e0, 0xc000ebff50}, {0x229da80, 0xc0013bc1e0})
	/src/rego/rego.go:1914 +0x20d
github.com/open-policy-agent/opa/rego.(*Rego).prepare(0xc0010ca700, {0x22990e0, 0xc000eea1b0}, 0x0?, {0xc0008d4c58, 0x1, 0x1})
	/src/rego/rego.go:1708 +0x1a9
github.com/open-policy-agent/opa/rego.(*Rego).PrepareForEval(0xc0010ca700, {0x22990e0, 0xc000eea1b0}, {0x0, 0x0, 0x0})
	/src/rego/rego.go:1561 +0x538
github.com/open-policy-agent/opa/rego.(*Rego).Eval(0xc0010ca700, {0x22990e0, 0xc000eea1b0})
	/src/rego/rego.go:1267 +0xb0
github.com/open-policy-agent/opa/server/authorizer.(*Basic).ServeHTTP(0xc000481a40, {0x2296820, 0xc000ec0378}, 0xc000d6f7d8?)
	/src/server/authorizer/authorizer.go:113 +0x310
net/http.HandlerFunc.ServeHTTP(0x7f793d12c5b8?, {0x2296820?, 0xc000ec0378?}, 0xc000ebfb60?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/open-policy-agent/opa/internal/prometheus.(*Provider).InstrumentHandler.func1({0x7f791458e8e0?, 0xc000ebfb60}, 0xc0013be300)
	/src/internal/prometheus/prometheus.go:100 +0x158
net/http.HandlerFunc.ServeHTTP(0x2296a00?, {0x7f791458e8e0?, 0xc000ebfb60?}, 0x6b5285?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1({0x2296a00, 0xc0004a2050}, 0xc0013be300)
	/src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:97 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc000eea0c0?, {0x2296a00?, 0xc0004a2050?}, 0x30?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/open-policy-agent/opa/server/identifier.(*TokenBased).ServeHTTP(0xc000294bc0, {0x2296a00, 0xc0004a2050}, 0xc0013be300)
	/src/server/identifier/token.go:32 +0xae
github.com/open-policy-agent/opa/server/handlers.CompressHandler.func1({0x2296a00?, 0xc0004a2050}, 0xc0013be300)
	/src/server/handlers/compress.go:34 +0x393
net/http.HandlerFunc.ServeHTTP(0xc00049c0e0?, {0x2296a00?, 0xc0004a2050?}, 0x7?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/open-policy-agent/opa/runtime.(*LoggingHandler).ServeHTTP(0xc00029bcb0, {0x2297b10, 0xc0010be060}, 0xc0013be200)
	/src/runtime/logging.go:116 +0xa70
net/http.serverHandler.ServeHTTP({0x5?}, {0x2297b10, 0xc0010be060}, 0xc0013be200)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.initALPNRequest.ServeHTTP({{0x22990e0?, 0xc0015060c0?}, 0xc001508380?, {0xc0003c80f0?}}, {0x2297b10, 0xc0010be060}, 0xc0013be200)
	/usr/local/go/src/net/http/server.go:3545 +0x245
net/http.(*http2serverConn).runHandler(0x22990e0?, 0xc000d28900?, 0xc0000e2ea0?, 0xc000d11d10?)
	/usr/local/go/src/net/http/h2_bundle.go:6049 +0x83
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5762 +0x68a

goroutine 1 [select]:
github.com/open-policy-agent/opa/runtime.(*Runtime).Serve(0xc00015ac80, {0x2299070, 0xc00004a018})
	/src/runtime/runtime.go:586 +0x1a0d
github.com/open-policy-agent/opa/runtime.(*Runtime).StartServer(0x0?, {0x2299070?, 0xc00004a018?})
	/src/runtime/runtime.go:420 +0x25
github.com/open-policy-agent/opa/cmd.startRuntime({0x2299070?, 0xc00004a018?}, 0xc0001d8fa8?, 0xc0?)
	/src/cmd/run.go:333 +0x39
github.com/open-policy-agent/opa/cmd.init.12.func1(0xc000031200?, {0xc00011a8c0, 0x1, 0xa})
	/src/cmd/run.go:184 +0x177
github.com/spf13/cobra.(*Command).execute(0xc000031200, {0xc00011a780, 0xa, 0xa})
	/src/vendor/github.com/spf13/cobra/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2d7bf80)
	/src/vendor/github.com/spf13/cobra/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
	/src/vendor/github.com/spf13/cobra/command.go:992 +0x19
main.main()
	/src/main.go:14 +0x25

goroutine 90 [IO wait]:
internal/poll.runtime_pollWait(0x7f79148194a8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000174000?, 0x4?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000174000)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc000174000)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000170030)
	/usr/local/go/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).AcceptTCP(0xc000170030)
	/usr/local/go/src/net/tcpsock.go:284 +0x3d
github.com/open-policy-agent/opa/server.tcpKeepAliveListener.Accept({0x20?})
	/src/server/server.go:432 +0x1d
crypto/tls.(*listener).Accept(0xc000170048)
	/usr/local/go/src/crypto/tls/tls.go:66 +0x2d
net/http.(*Server).Serve(0xc0003c80f0, {0x2295e00, 0xc000170048})
	/usr/local/go/src/net/http/server.go:3059 +0x385
net/http.(*Server).ServeTLS(0xc0003c80f0, {0x2298260?, 0xc000170030}, {0x0, 0x0}, {0x0, 0x0})
	/usr/local/go/src/net/http/server.go:3129 +0x4bd
github.com/open-policy-agent/opa/server.(*baseHTTPListener).ListenAndServeTLS(0xc0004a30e0, {0x0, 0x0}, {0x0, 0x0})
	/src/server/server.go:527 +0x165
github.com/open-policy-agent/opa/server.(*Server).getListenerForHTTPSServer.func1()
	/src/server/server.go:623 +0x2c
github.com/open-policy-agent/opa/runtime.(*Runtime).Serve.func4(0xc00068f620?)
	/src/runtime/runtime.go:564 +0x25
created by github.com/open-policy-agent/opa/runtime.(*Runtime).Serve
	/src/runtime/runtime.go:563 +0x1745

goroutine 91 [IO wait]:
internal/poll.runtime_pollWait(0x7f7914819598, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0001ae000?, 0x4?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0001ae000)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc0001ae000)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000380000)
	/usr/local/go/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).AcceptTCP(0xc000380000)
	/usr/local/go/src/net/tcpsock.go:284 +0x3d
github.com/open-policy-agent/opa/server.tcpKeepAliveListener.Accept({0x958b2d?})
	/src/server/server.go:432 +0x1d
net/http.(*Server).Serve(0xc0003c81e0, {0x2298260, 0xc000380000})
	/usr/local/go/src/net/http/server.go:3059 +0x385
github.com/open-policy-agent/opa/server.(*baseHTTPListener).ListenAndServe(0xc0004a3130)
	/src/server/server.go:494 +0xb9
github.com/open-policy-agent/opa/runtime.(*Runtime).Serve.func4(0x0?)
	/src/runtime/runtime.go:564 +0x25
created by github.com/open-policy-agent/opa/runtime.(*Runtime).Serve
	/src/runtime/runtime.go:563 +0x1745

goroutine 93 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 260 [IO wait]:
internal/poll.runtime_pollWait(0x7f79148191d8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc001504080?, 0xc0002a4240?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001504080, {0xc0002a4240, 0x240, 0x240})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc001504080, {0xc0002a4240?, 0xc0002a4245?, 0x1a?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000e32008, {0xc0002a4240?, 0x1e?, 0xc001508530?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0010ac030, {0xc0002a4240?, 0xc0010ac030?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc001508610, {0x228dcc0, 0xc0010ac030})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc001508380, {0x2290300?, 0xc000e32008}, 0x240?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc001508380, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc001508380, {0xc001220120, 0x9, 0x30?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
io.ReadAtLeast({0x7f79148390f8, 0xc001508380}, {0xc001220120, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
net/http.http2readFrameHeader({0xc001220120?, 0x9?, 0xc00080a060?}, {0x7f79148390f8?, 0xc001508380?})
	/usr/local/go/src/net/http/h2_bundle.go:1567 +0x6e
net/http.(*http2Framer).ReadFrame(0xc0012200e0)
	/usr/local/go/src/net/http/h2_bundle.go:1831 +0x95
net/http.(*http2serverConn).readFrames(0xc0001a89c0)
	/usr/local/go/src/net/http/h2_bundle.go:4560 +0x91
created by net/http.(*http2serverConn).serve
	/usr/local/go/src/net/http/h2_bundle.go:4667 +0x55c

goroutine 226 [select]:
net/http.(*http2serverConn).serve(0xc001510340)
	/usr/local/go/src/net/http/h2_bundle.go:4675 +0x8ac
net/http.(*http2Server).ServeConn(0xc0001720a0, {0x229e390?, 0xc001508000}, 0xc001531b20)
	/usr/local/go/src/net/http/h2_bundle.go:4270 +0xbe5
net/http.http2ConfigureServer.func1(0xc0003c80f0, 0x229e390?, {0x2292120, 0xc0013bc0e0})
	/usr/local/go/src/net/http/h2_bundle.go:4060 +0xff
net/http.(*conn).serve(0xc00150c000, {0x22990e0, 0xc00016c150})
	/usr/local/go/src/net/http/server.go:1903 +0x1293
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed

goroutine 227 [select]:
net/http.(*http2serverConn).serve(0xc0001a89c0)
	/usr/local/go/src/net/http/h2_bundle.go:4675 +0x8ac
net/http.(*http2Server).ServeConn(0xc0001720a0, {0x229e390?, 0xc001508380}, 0xc00152db20)
	/usr/local/go/src/net/http/h2_bundle.go:4270 +0xbe5
net/http.http2ConfigureServer.func1(0xc0003c80f0, 0x229e390?, {0x2292120, 0xc000eb0040})
	/usr/local/go/src/net/http/h2_bundle.go:4060 +0xff
net/http.(*conn).serve(0xc00150c090, {0x22990e0, 0xc00016c150})
	/usr/local/go/src/net/http/server.go:1903 +0x1293
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed

goroutine 244 [IO wait]:
internal/poll.runtime_pollWait(0x7f79148193b8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc001504000?, 0xc0002a4900?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001504000, {0xc0002a4900, 0x240, 0x240})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc001504000, {0xc0002a4900?, 0xc0002a4905?, 0xe1e1d0?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000e32000, {0xc0002a4900?, 0x155?, 0xc0000b7900?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00061a048, {0xc0002a4900?, 0xc00061a048?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc001508290, {0x228dcc0, 0xc00061a048})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc001508000, {0x2290300?, 0xc000e32000}, 0x240?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc001508000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc001508000, {0xc000a2a200, 0x9, 0x30?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
io.ReadAtLeast({0x7f79148390f8, 0xc001508000}, {0xc000a2a200, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
net/http.http2readFrameHeader({0xc000a2a200?, 0x9?, 0xc000ebf4a0?}, {0x7f79148390f8?, 0xc001508000?})
	/usr/local/go/src/net/http/h2_bundle.go:1567 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000a2a1c0)
	/usr/local/go/src/net/http/h2_bundle.go:1831 +0x95
net/http.(*http2serverConn).readFrames(0xc001510340)
	/usr/local/go/src/net/http/h2_bundle.go:4560 +0x91
created by net/http.(*http2serverConn).serve
	/usr/local/go/src/net/http/h2_bundle.go:4667 +0x55c

goroutine 246 [runnable]:
github.com/open-policy-agent/opa/ast.localDeclaredVars.Insert(...)
	/src/ast/compile.go:4730
github.com/open-policy-agent/opa/ast.(*ruleArgLocalRewriter).Visit(0xc0006ee7b0, {0x1db2d00?, 0xc000de0e70})
	/src/ast/compile.go:2427 +0x679
github.com/open-policy-agent/opa/ast.walk({0x228e460?, 0xc0006ee7b0?}, {0x1db2d00?, 0xc000de0e70?})
	/src/ast/visit.go:46 +0x68
github.com/open-policy-agent/opa/ast.Walk({0x228e460, 0xc0006ee7b0}, {0x1db2d00, 0xc000de0e70})
	/src/ast/visit.go:30 +0x145
github.com/open-policy-agent/opa/ast.(*Compiler).rewriteLocalArgVars(0xc0001a4500, 0xc000e4ffc0, 0xc000a3a400, 0xc000c47b80)
	/src/ast/compile.go:2399 +0xc8
github.com/open-policy-agent/opa/ast.(*Compiler).rewriteLocalVars.func1(0xc000c47b80)
	/src/ast/compile.go:2216 +0x2bc
github.com/open-policy-agent/opa/ast.WalkRules.func1({0x1da20c0?, 0xc000c47b80?})
	/src/ast/visit.go:245 +0x42
github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk(0xc0015447c8, {0x1da20c0?, 0xc000c47b80?})
	/src/ast/visit.go:286 +0x5f
github.com/open-policy-agent/opa/ast.(*GenericVisitor).Walk(0xc0015447c8, {0x1d29ba0?, 0xc000175600?})
	/src/ast/visit.go:297 +0xd6a
github.com/open-policy-agent/opa/ast.WalkRules({0x1d29ba0, 0xc000175600}, 0xc0006ceae0)
	/src/ast/visit.go:254 +0x9a
github.com/open-policy-agent/opa/ast.(*Compiler).rewriteLocalVars(0xc0001a4500)
	/src/ast/compile.go:2207 +0x48
github.com/open-policy-agent/opa/ast.(*Compiler).runStage(0x22964f0?, {0x1e36dbf?, 0x1e19bb7?}, 0xb?)
	/src/ast/compile.go:1383 +0xec
github.com/open-policy-agent/opa/ast.(*Compiler).compile(0xc0001a4500)
	/src/ast/compile.go:1403 +0xd8
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc0001a4500, 0xc000a34040)
	/src/ast/compile.go:457 +0x3b5
github.com/open-policy-agent/opa/bundle.compileModules(0xc0001a4500, {0x229da80, 0xc0013bc180}, 0x2a?, 0x228e9e0?, 0x0)
	/src/bundle/store.go:788 +0x3a5
github.com/open-policy-agent/opa/bundle.activateBundles(0xc000a349d8)
	/src/bundle/store.go:453 +0x78b
github.com/open-policy-agent/opa/bundle.Activate(...)
	/src/bundle/store.go:310
github.com/open-policy-agent/opa/rego.(*Rego).compileModules(0xc0010ca380, {0x22990e0, 0xc000ebf4d0}, {0x228e9e0, 0xc0010de030}, {0x229da80, 0xc0013bc180})
	/src/rego/rego.go:1914 +0x20d
github.com/open-policy-agent/opa/rego.(*Rego).prepare(0xc0010ca380, {0x22990e0, 0xc000ebf4d0}, 0x0?, {0xc000a34c58, 0x1, 0x1})
	/src/rego/rego.go:1708 +0x1a9
github.com/open-policy-agent/opa/rego.(*Rego).PrepareForEval(0xc0010ca380, {0x22990e0, 0xc000ebf4d0}, {0x0, 0x0, 0x0})
	/src/rego/rego.go:1561 +0x538
github.com/open-policy-agent/opa/rego.(*Rego).Eval(0xc0010ca380, {0x22990e0, 0xc000ebf4d0})
	/src/rego/rego.go:1267 +0xb0
github.com/open-policy-agent/opa/server/authorizer.(*Basic).ServeHTTP(0xc000481a40, {0x2296820, 0xc000ec0330}, 0xc000d6d7d8?)
	/src/server/authorizer/authorizer.go:113 +0x310
net/http.HandlerFunc.ServeHTTP(0x7f793d12c5b8?, {0x2296820?, 0xc000ec0330?}, 0xc000ebf710?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/open-policy-agent/opa/internal/prometheus.(*Provider).InstrumentHandler.func1({0x7f791458e8e0?, 0xc000ebf710}, 0xc001038400)
	/src/internal/prometheus/prometheus.go:100 +0x158
net/http.HandlerFunc.ServeHTTP(0x2296a00?, {0x7f791458e8e0?, 0xc000ebf710?}, 0x6b5285?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1({0x2296a00, 0xc000dc5450}, 0xc001038400)
	/src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:97 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc000ebf410?, {0x2296a00?, 0xc000dc5450?}, 0x30?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/open-policy-agent/opa/server/identifier.(*TokenBased).ServeHTTP(0xc000294bc0, {0x2296a00, 0xc000dc5450}, 0xc001038400)
	/src/server/identifier/token.go:32 +0xae
github.com/open-policy-agent/opa/server/handlers.CompressHandler.func1({0x2296a00?, 0xc000dc5450}, 0xc001038400)
	/src/server/handlers/compress.go:34 +0x393
net/http.HandlerFunc.ServeHTTP(0xc00049c0e0?, {0x2296a00?, 0xc000dc5450?}, 0x7?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/open-policy-agent/opa/runtime.(*LoggingHandler).ServeHTTP(0xc00029bcb0, {0x2297b10, 0xc000be0008}, 0xc001038300)
	/src/runtime/logging.go:116 +0xa70
net/http.serverHandler.ServeHTTP({0x0?}, {0x2297b10, 0xc000be0008}, 0xc001038300)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.initALPNRequest.ServeHTTP({{0x22990e0?, 0xc0015060f0?}, 0xc001508000?, {0xc0003c80f0?}}, {0x2297b10, 0xc000be0008}, 0xc001038300)
	/usr/local/go/src/net/http/server.go:3545 +0x245
net/http.(*http2serverConn).runHandler(0x10?, 0xd4?, 0x0?, 0x0?)
	/usr/local/go/src/net/http/h2_bundle.go:6049 +0x83
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5762 +0x68a
```

**Comment by alex0z1** [comment]
@ashutosh-narkar  just tested 0.55 and I can't reproduce the issue anymore. Thank you!
