### ISSUE TITLE
opa eval: panic when given bad input for --unknowns

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#7127]
`opa eval --help` says

```
-u, --unknowns stringArray                                      set paths to treat as unknown during partial evaluation (default [input])
```

so it's not completely out of the question to try setting it to `[input,data.posts]`. When you get then is a panic:

```
% opa eval --partial -d q.rego -fpretty -u '[input,data.posts]' data.example.allow
panic: illegal value

goroutine 1 [running]:
github.com/open-policy-agent/opa/topdown.newSaveSetElem(...)
	/Users/stephan/Sources/open-policy-agent/opa/topdown/save.go:132
github.com/open-policy-agent/opa/topdown.(*saveSet).Push(0xc0000177a0, {0xc000135c20, 0x1, 0x100071205?}, 0xc000020180)
	/Users/stephan/Sources/open-policy-agent/opa/topdown/save.go:31 +0x434
github.com/open-policy-agent/opa/topdown.newSaveSet({0xc000135c20, 0x1, 0x1}, 0xc000020180, 0x0)
	/Users/stephan/Sources/open-policy-agent/opa/topdown/save.go:26 +0xbb
github.com/open-policy-agent/opa/topdown.(*Query).PartialRun(0xc000425180, {0x101f32350, 0x102a8b840})
	/Users/stephan/Sources/open-policy-agent/opa/topdown/query.go:370 +0x72e
github.com/open-policy-agent/opa/rego.(*Rego).partial(0xc0003c6e08, {0x101f32350, 0x102a8b840}, 0xc000365860)
	/Users/stephan/Sources/open-policy-agent/opa/rego/rego.go:2455 +0x93c
github.com/open-policy-agent/opa/rego.PreparedPartialQuery.Partial({{0xc0003c6e08?, 0xc0004034d0?}}, {0x101f32350, 0x102a8b840}, {0xc000445c90?, 0xc0000d98c0?, 0x1035df108?})
	/Users/stephan/Sources/open-policy-agent/opa/rego/rego.go:507 +0x149
github.com/open-policy-agent/opa/cmd.evalOnce({0x101f32350, 0x102a8b840}, 0xc0001bd200)
	/Users/stephan/Sources/open-policy-agent/opa/cmd/eval.go:472 +0xf07
github.com/open-policy-agent/opa/cmd.eval({_, _, _}, {0xc000402a50, 0x0, 0x1, {0xc000444e30, 0x1, 0x1}, {0x102a8b840, ...}, ...}, ...)
	/Users/stephan/Sources/open-policy-agent/opa/cmd/eval.go:374 +0x3f0
github.com/open-policy-agent/opa/cmd.init.5.func2(0xc0003f2f08?, {0xc000376380?, 0x4?, 0x1019e5a41?})
	/Users/stephan/Sources/open-policy-agent/opa/cmd/eval.go:292 +0x6e
github.com/spf13/cobra.(*Command).execute(0xc0003f2f08, {0xc000376310, 0x7, 0x7})
	/Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x102a4cc80)
	/Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
	/Users/stephan/Sources/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:1041 +0x13
main.main()
	/Users/stephan/Sources/open-policy-agent/opa/main.go:14 +0x1a
```

It would be nicer if we told the user that their argument to `--unknowns` is of the wrong type.

(BTW the right format would be `--unknowns input --unknowns data.posts`)

**Comment by srenatus** [comment]
@kd-labs wants to take a look
