### ISSUE TITLE
Various *.rego inputs that cause panics

### ISSUE THREAD

**Issue by aeneasr** [open-policy-agent/opa#948]
All of these are reproducible when running `--serve` instead of REPL.

### File with single `.`

```
$ opa run
OPA 0.9.1 (commit d5ba22b7, built at 2018-08-16T15:46:52Z)

Run 'help' to see a list of commands.

> .
| 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.newParserErrorDetail(0xc4201d3050, 0x2, 0x8, 0x2, 0x0, 0x1, 0x0)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:708 +0x16f
github.com/open-policy-agent/opa/ast.formatParserError(0x0, 0x0, 0xc4201d3050, 0x2, 0x8, 0xc4201c2d20, 0xc4202976b0)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:521 +0x19f
github.com/open-policy-agent/opa/ast.formatParserErrors(0x0, 0x0, 0xc4201d3050, 0x2, 0x8, 0x1709500, 0xc4201d5940, 0x2, 0x0)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:505 +0x135
github.com/open-policy-agent/opa/ast.ParseStatements(0x0, 0x0, 0xc4201d3048, 0x2, 0x1, 0xc4201d3048, 0x2, 0xc420297900, 0x1040845, 0xc4201d5420, ...)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:470 +0x6af
github.com/open-policy-agent/opa/repl.(*REPL).evalBufferMulti(0xc4201d0900, 0x170e9c0, 0xc4200220c0, 0x1, 0x2)
	/go/src/github.com/open-policy-agent/opa/repl/repl.go:663 +0x12e
github.com/open-policy-agent/opa/repl.(*REPL).OneShot(0xc4201d0900, 0x170e9c0, 0xc4200220c0, 0xc4201d3044, 0x0, 0x0, 0x0)
	/go/src/github.com/open-policy-agent/opa/repl/repl.go:278 +0x1be
github.com/open-policy-agent/opa/repl.(*REPL).Loop(0xc4201d0900, 0x170e9c0, 0xc4200220c0)
	/go/src/github.com/open-policy-agent/opa/repl/repl.go:178 +0x303
github.com/open-policy-agent/opa/runtime.(*Runtime).StartREPL(0xc4201a4ea0, 0x170e9c0, 0xc4200220c0)
	/go/src/github.com/open-policy-agent/opa/runtime/runtime.go:289 +0x1d7
github.com/open-policy-agent/opa/cmd.init.4.func1(0xc42016e480, 0x1a4af00, 0x0, 0x0)
	/go/src/github.com/open-policy-agent/opa/cmd/run.go:122 +0x4fd
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).execute(0xc42016e480, 0x1a4af00, 0x0, 0x0, 0xc42016e480, 0x1a4af00)
	/go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a24040, 0xc4201d9f68, 0x1533055, 0xc4201d9f78)
	/go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:726 +0x2d4
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a24040, 0x2, 0xc420161da0)
	/go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/go/src/github.com/open-policy-agent/opa/main.go:12 +0x2d
```

### File with single `-`

```
$ opa run
OPA 0.9.1 (commit d5ba22b7, built at 2018-08-16T15:46:52Z)

Run 'help' to see a list of commands.

> -
| 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.newParserErrorDetail(0xc4201dd068, 0x2, 0x8, 0x2, 0x0, 0x1, 0x0)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:708 +0x16f
github.com/open-policy-agent/opa/ast.formatParserError(0x0, 0x0, 0xc4201dd068, 0x2, 0x8, 0xc4201cccd0, 0xc4202a36b0)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:521 +0x19f
github.com/open-policy-agent/opa/ast.formatParserErrors(0x0, 0x0, 0xc4201dd068, 0x2, 0x8, 0x1709500, 0xc4201dee00, 0x2, 0x0)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:505 +0x135
github.com/open-policy-agent/opa/ast.ParseStatements(0x0, 0x0, 0xc4201dd060, 0x2, 0x1, 0xc4201dd060, 0x2, 0xc4202a3900, 0x1040845, 0xc4201de900, ...)
	/go/src/github.com/open-policy-agent/opa/ast/parser_ext.go:470 +0x6af
github.com/open-policy-agent/opa/repl.(*REPL).evalBufferMulti(0xc4201da7e0, 0x170e9c0, 0xc4200220c0, 0x1, 0x2)
	/go/src/github.com/open-policy-agent/opa/repl/repl.go:663 +0x12e
github.com/open-policy-agent/opa/repl.(*REPL).OneShot(0xc4201da7e0, 0x170e9c0, 0xc4200220c0, 0xc4201dd04c, 0x0, 0x0, 0x0)
	/go/src/github.com/open-policy-agent/opa/repl/repl.go:278 +0x1be
github.com/open-policy-agent/opa/repl.(*REPL).Loop(0xc4201da7e0, 0x170e9c0, 0xc4200220c0)
	/go/src/github.com/open-policy-agent/opa/repl/repl.go:178 +0x303
github.com/open-policy-agent/opa/runtime.(*Runtime).StartREPL(0xc4201aed80, 0x170e9c0, 0xc4200220c0)
	/go/src/github.com/open-policy-agent/opa/runtime/runtime.go:289 +0x1d7
github.com/open-policy-agent/opa/cmd.init.4.func1(0xc420206240, 0x1a4af00, 0x0, 0x0)
	/go/src/github.com/open-policy-agent/opa/cmd/run.go:122 +0x4fd
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).execute(0xc420206240, 0x1a4af00, 0x0, 0x0, 0xc420206240, 0x1a4af00)
	/go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a24040, 0xc4201e3f68, 0x1533055, 0xc4201e3f78)
	/go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:726 +0x2d4
github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a24040, 0x2, 0xc42018fd40)
	/go/src/github.com/open-policy-agent/opa/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/go/src/github.com/open-policy-agent/opa/main.go:12 +0x2d
```

I think it would generally be a good idea to run something like `go-fuzz` against this.

If I find more, I will report it.

**Comment by tsandall** [comment]
Seems this is caused by recent improvements that try to rewind the error position: https://github.com/open-policy-agent/opa/pull/854/files#diff-c630f47ad9a72b701cce17e6e2c53e87R708.

**Comment by aeneasr** [comment]
I ran about ~15m more test cases with a very simple fuzzing algorithm and was unable to find any other issues. When I wrote it I didn't know how to embed the OPA compiler in Go properly so I just ran `opa run` against it and it's thus extremely slow. You can find the source code [here](https://github.com/aeneasr/opa-fuzz/tree/master). Due to the terrible performance you won't able to get a lot of chars out of it and it tests all 255 bits per byte. If I find some free time I might improve it, but it seems that `.\n` and `-\n` where the only issues I was able to find so far.

**Comment by aeneasr** [comment]
Actually, it did find some more but they're always a combination with `-` and `.` and an appended or prepended char. For example `092d0a` and `092e0a` and `2d0a` and `2e0a` (all hex) also cause a panic.

**Comment by aeneasr** [comment]
No problem! The code was so terrible so I quickly rewrote it with the help you gave wrt using rego as a library. It's now much faster and found more panics along the way, e.g.:

```
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 2378
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 2379
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237a
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237b
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237c
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237d
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237e
Panic caused by "runtime error: invalid memory address or nil pointer dereference" was thrown with payload 237f
Panic caused by "runtime error: index out of range" was thrown with payload 2d0a
Panic caused by "runtime error: index out of range" was thrown with payload 2e0a
```

You can run it with `go get github.com/aeneasr/opa-fuzz` and then `opa-fuzz -len 4` where the `-len` flag sets what the longest combination is that you want to test (here it's 4 chars). Hope it helps!

**Comment by aeneasr** [comment]
This can obviously be improved by running some go-routines with all available cores, but I guess most errors have the same root cause anyways so I'm not sure if it's worth the time right now.

**Comment by aeneasr** [comment]
Oh, and obviously it would be much more interesting to see which `rego.Input` values may cause some unexpected behavior. This is really the spot where unexpected input may cause havok as it's probably unsanitized. Since I'm not seeing some serious (de-)serialization (at least from the publicly visible API, no idea about internals obviously) I don't think it's there, but it could be worth a shot!

**Comment by aeneasr** [comment]
Nice!
